// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ALUExeUnit(	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
  input         clock,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
                reset,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
                io_kill,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:79:19
  input  [7:0]  io_brupdate_b1_resolve_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:80:23
                io_brupdate_b1_mispredict_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:80:23
  input         io_iss_uop_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_is_rvc,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_fu_code_0,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_iw_p1_bypass_hint,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_iw_p2_bypass_hint,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [7:0]  io_iss_uop_bits_br_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [2:0]  io_iss_uop_bits_br_tag,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [3:0]  io_iss_uop_bits_br_type,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input         io_iss_uop_bits_is_sfb,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_is_mov,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [3:0]  io_iss_uop_bits_ftq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input         io_iss_uop_bits_edge_inst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [5:0]  io_iss_uop_bits_pc_lob,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input         io_iss_uop_bits_taken,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [2:0]  io_iss_uop_bits_imm_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [4:0]  io_iss_uop_bits_pimm,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [1:0]  io_iss_uop_bits_op1_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [2:0]  io_iss_uop_bits_op2_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [4:0]  io_iss_uop_bits_rob_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [5:0]  io_iss_uop_bits_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_prs1,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_prs2,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [3:0]  io_iss_uop_bits_ppred,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [2:0]  io_iss_uop_bits_csr_cmd,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input         io_iss_uop_bits_ldst_is_rs1,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [1:0]  io_iss_uop_bits_dst_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_lrs1_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
                io_iss_uop_bits_lrs2_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input         io_iss_uop_bits_fcn_dw,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  input  [4:0]  io_iss_uop_bits_fcn_op,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:90:22
  output        io_arb_irf_reqs_0_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:106:27
  output [5:0]  io_arb_irf_reqs_0_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:106:27
  output        io_arb_irf_reqs_1_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:106:27
  output [5:0]  io_arb_irf_reqs_1_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:106:27
  input         io_arb_rebusys_0_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:107:27
  input  [5:0]  io_arb_rebusys_0_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:107:27
  input         io_arb_rebusys_0_bits_rebusy,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:107:27
  input  [63:0] io_rrd_irf_resps_0,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:108:31
                io_rrd_irf_resps_1,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:108:31
  input         io_rrd_irf_bypasses_0_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:109:31
  input  [5:0]  io_rrd_irf_bypasses_0_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:109:31
  input  [63:0] io_rrd_irf_bypasses_0_bits_data,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:109:31
  input         io_rrd_irf_bypasses_1_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:109:31
  input  [5:0]  io_rrd_irf_bypasses_1_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:109:31
  input  [63:0] io_rrd_irf_bypasses_1_bits_data,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:109:31
  output [3:0]  io_arb_prf_req_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:179:29
  input         io_rrd_prf_resp,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:181:29
  output [4:0]  io_arb_immrf_req_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:151:31
  input  [63:0] io_rrd_immrf_resp,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:153:31
  output        io_rrd_immrf_wakeup_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:154:31
  output [4:0]  io_rrd_immrf_wakeup_bits_uop_pimm,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:154:31
  output [2:0]  io_arb_brf_req_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:192:29
  input  [3:0]  io_rrd_brf_resp_ldq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:194:29
                io_rrd_brf_resp_stq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:194:29
  input         io_arb_ftq_reqs_0_ready,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:240:28
  output        io_arb_ftq_reqs_0_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:240:28
  output [3:0]  io_arb_ftq_reqs_0_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:240:28
  input         io_arb_ftq_reqs_1_ready,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:240:28
  output        io_arb_ftq_reqs_1_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:240:28
  output [3:0]  io_arb_ftq_reqs_1_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:240:28
  input         io_rrd_ftq_resps_0_entry_cfi_idx_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:241:28
  input  [1:0]  io_rrd_ftq_resps_0_entry_cfi_idx_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:241:28
  input         io_rrd_ftq_resps_0_entry_start_bank,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:241:28
  input  [39:0] io_rrd_ftq_resps_0_pc,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:241:28
  input         io_rrd_ftq_resps_1_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:241:28
  input  [39:0] io_rrd_ftq_resps_1_pc,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:241:28
  output        io_fast_wakeup_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:503:26
  output [5:0]  io_fast_wakeup_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:503:26
  output [1:0]  io_fast_wakeup_bits_uop_dst_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:503:26
  output        io_fast_pred_wakeup_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:513:31
  output [5:0]  io_fast_pred_wakeup_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:513:31
  output        io_squash_iss,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:521:25
                io_child_rebusy,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:528:27
                io_alu_resp_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output [7:0]  io_alu_resp_bits_uop_br_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output [3:0]  io_alu_resp_bits_uop_br_type,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output        io_alu_resp_bits_uop_is_sfb,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output [4:0]  io_alu_resp_bits_uop_rob_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output [5:0]  io_alu_resp_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output [1:0]  io_alu_resp_bits_uop_dst_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output [63:0] io_alu_resp_bits_data,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
  output        io_alu_resp_bits_predicated,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:565:23
                io_brinfo_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
                io_brinfo_bits_uop_is_rvc,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [7:0]  io_brinfo_bits_uop_br_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [2:0]  io_brinfo_bits_uop_br_tag,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [3:0]  io_brinfo_bits_uop_ftq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output        io_brinfo_bits_uop_edge_inst,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [5:0]  io_brinfo_bits_uop_pc_lob,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [4:0]  io_brinfo_bits_uop_rob_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [3:0]  io_brinfo_bits_uop_ldq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
                io_brinfo_bits_uop_stq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output        io_brinfo_bits_mispredict,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
                io_brinfo_bits_taken,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [2:0]  io_brinfo_bits_cfi_type,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [1:0]  io_brinfo_bits_pc_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [39:0] io_brinfo_bits_jalr_target,	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
  output [20:0] io_brinfo_bits_target_offset	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:569:21
);

  reg         arb_uop_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_fu_code_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_iw_p1_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_iw_p2_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [7:0]  arb_uop_bits_br_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [2:0]  arb_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [3:0]  arb_uop_bits_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_is_mov;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [3:0]  arb_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [5:0]  arb_uop_bits_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_taken;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [2:0]  arb_uop_bits_imm_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [4:0]  arb_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [1:0]  arb_uop_bits_op1_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [2:0]  arb_uop_bits_op2_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [4:0]  arb_uop_bits_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [5:0]  arb_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [5:0]  arb_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [5:0]  arb_uop_bits_prs2;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [3:0]  arb_uop_bits_ppred;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [2:0]  arb_uop_bits_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_ldst_is_rs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [1:0]  arb_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [1:0]  arb_uop_bits_lrs1_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [1:0]  arb_uop_bits_lrs2_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         arb_uop_bits_fcn_dw;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg  [4:0]  arb_uop_bits_fcn_op;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
  reg         rrd_uop_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_fu_code_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_iw_p1_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_iw_p2_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [7:0]  rrd_uop_bits_br_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [2:0]  rrd_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [3:0]  rrd_uop_bits_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_is_mov;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [3:0]  rrd_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [5:0]  rrd_uop_bits_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_taken;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [2:0]  rrd_uop_bits_imm_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [4:0]  rrd_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [1:0]  rrd_uop_bits_op1_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [2:0]  rrd_uop_bits_op2_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [4:0]  rrd_uop_bits_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [5:0]  rrd_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [5:0]  rrd_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [5:0]  rrd_uop_bits_prs2;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [2:0]  rrd_uop_bits_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_ldst_is_rs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [1:0]  rrd_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [1:0]  rrd_uop_bits_lrs1_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [1:0]  rrd_uop_bits_lrs2_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         rrd_uop_bits_fcn_dw;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg  [4:0]  rrd_uop_bits_fcn_op;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20
  reg         exe_uop_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_fu_code_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [7:0]  exe_uop_bits_br_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [2:0]  exe_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [3:0]  exe_uop_bits_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_is_mov;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [3:0]  exe_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [5:0]  exe_uop_bits_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_taken;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [4:0]  exe_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [1:0]  exe_uop_bits_op1_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [2:0]  exe_uop_bits_op2_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [4:0]  exe_uop_bits_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [3:0]  exe_uop_bits_ldq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [3:0]  exe_uop_bits_stq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [5:0]  exe_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [5:0]  exe_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [2:0]  exe_uop_bits_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_ldst_is_rs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [1:0]  exe_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg         exe_uop_bits_fcn_dw;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  reg  [4:0]  exe_uop_bits_fcn_op;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
  wire        _arb_rebusied_prs1_T = arb_uop_bits_lrs1_rtype == 2'h0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :121:72
  wire        _arb_rebusied_prs2_T = arb_uop_bits_lrs2_rtype == 2'h0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :121:72, :125:74
  wire        _arb_rebusied_prs2_T_1 =
    io_arb_rebusys_0_valid & io_arb_rebusys_0_bits_rebusy;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:118:39
  wire        arb_rebusied =
    _arb_rebusied_prs1_T & _arb_rebusied_prs2_T_1
    & io_arb_rebusys_0_bits_uop_pdst == arb_uop_bits_prs1 | _arb_rebusied_prs2_T
    & _arb_rebusied_prs2_T_1 & io_arb_rebusys_0_bits_uop_pdst == arb_uop_bits_prs2;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :118:{39,75}, :121:72, :125:74, :128:62, :129:62, :130:45
  reg  [63:0] exe_rs1_data;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:133:25
  reg  [63:0] exe_rs2_data;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:134:25
  wire        hits_0 =
    io_rrd_irf_bypasses_0_valid
    & rrd_uop_bits_prs1 == io_rrd_irf_bypasses_0_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :113:{55,62}
  wire        hits_1 =
    io_rrd_irf_bypasses_1_valid
    & rrd_uop_bits_prs1 == io_rrd_irf_bypasses_1_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :113:{55,62}
  wire        rs1_hit = hits_0 | hits_1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:113:55, :114:19
  wire        hits_0_1 =
    io_rrd_irf_bypasses_0_valid
    & rrd_uop_bits_prs2 == io_rrd_irf_bypasses_0_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :113:{55,62}
  wire        hits_1_1 =
    io_rrd_irf_bypasses_1_valid
    & rrd_uop_bits_prs2 == io_rrd_irf_bypasses_1_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :113:{55,62}
  wire        rs2_hit = hits_0_1 | hits_1_1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:113:55, :114:19
  `ifndef SYNTHESIS	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:136:9
    always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:136:9
      if (~reset & rrd_uop_valid & rrd_uop_bits_lrs1_rtype == 2'h0
          & rrd_uop_bits_iw_p1_bypass_hint & ~rs1_hit) begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :114:19, :121:72, :136:{9,53,101}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:136:9
          $error("Assertion failed\n    at execution-unit.scala:136 assert(!(rrd_uop.valid && rrd_uop.bits.lrs1_rtype === RT_FIX && rrd_uop.bits.iw_p1_bypass_hint && !rs1_hit))\n");	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:136:9
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:136:9
          $fatal;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:136:9
      end
      if (~reset & rrd_uop_valid & rrd_uop_bits_lrs2_rtype == 2'h0
          & rrd_uop_bits_iw_p2_bypass_hint & ~rs2_hit) begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :114:19, :121:72, :136:9, :141:{11,55,103}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:141:11
          $error("Assertion failed\n    at execution-unit.scala:141 assert(!(rrd_uop.valid && rrd_uop.bits.lrs2_rtype === RT_FIX && rrd_uop.bits.iw_p2_bypass_hint && !rs2_hit))\n");	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:141:11
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:141:11
          $fatal;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:141:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg         exe_pred_data;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:186:26
  wire        _exe_imm_data_ip_T = rrd_uop_bits_imm_sel == 3'h6;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47
  wire        _exe_imm_data_T = rrd_uop_bits_imm_sel == 3'h5;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47
  reg  [63:0] exe_imm_data;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:170:29
  wire        io_arb_ftq_reqs_0_valid_0 =
    arb_uop_valid
    & (arb_uop_bits_op1_sel == 2'h2 | (|arb_uop_bits_br_type) & arb_uop_bits_is_sfb);	// generators/boom/src/main/scala/v4/common/micro-op.scala:120:{34,42}, generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :244:{45,70,81}
  wire        io_arb_ftq_reqs_1_valid_0 =
    arb_uop_valid
    & (arb_uop_bits_br_type == 4'h8 | (|arb_uop_bits_br_type) & arb_uop_bits_is_sfb);	// generators/boom/src/main/scala/v4/common/micro-op.scala:120:{34,42}, generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :248:{45,70,79}
  reg         exe_ftq_data_0_entry_cfi_idx_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  reg  [1:0]  exe_ftq_data_0_entry_cfi_idx_bits;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  reg         exe_ftq_data_0_entry_start_bank;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  reg  [39:0] exe_ftq_data_0_pc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  reg         exe_ftq_data_1_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  reg  [39:0] exe_ftq_data_1_pc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  wire        _io_squash_iss_output =
    io_arb_ftq_reqs_0_valid_0 & ~io_arb_ftq_reqs_0_ready | io_arb_ftq_reqs_1_valid_0
    & ~io_arb_ftq_reqs_1_ready;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:244:45, :248:45, :525:{47,50,77}, :526:{47,50}
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
    automatic logic [7:0]  _will_replay_T;	// generators/boom/src/main/scala/v4/util/util.scala:126:51
    automatic logic [19:0] exe_imm_data_ip =
      _exe_imm_data_ip_T ? 20'h0 : io_rrd_immrf_resp[19:0];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:153:31, :551:25, generators/boom/src/main/scala/v4/util/util.scala:301:17, generators/rocket-chip/src/main/scala/util/package.scala:16:47
    automatic logic        _exe_imm_data_i4_1_T;	// generators/boom/src/main/scala/v4/util/util.scala:304:27
    automatic logic        _exe_imm_data_i11_T_1;	// generators/boom/src/main/scala/v4/util/util.scala:305:44
    automatic logic        _GEN = _io_squash_iss_output | arb_rebusied;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:130:45, :525:77, :536:23
    _will_replay_T = io_brupdate_b1_mispredict_mask & arb_uop_bits_br_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, generators/boom/src/main/scala/v4/util/util.scala:126:51
    _exe_imm_data_i4_1_T = rrd_uop_bits_imm_sel == 3'h3;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, generators/boom/src/main/scala/v4/util/util.scala:304:27
    _exe_imm_data_i11_T_1 = rrd_uop_bits_imm_sel == 3'h4;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, generators/boom/src/main/scala/v4/util/util.scala:305:44
    if (_GEN) begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:536:23
      arb_uop_valid <= arb_uop_valid & ~((|_will_replay_T) | io_kill) & ~arb_rebusied;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :130:45, :537:{40,94,97}, generators/boom/src/main/scala/v4/util/util.scala:61:61, :126:{51,59}
      arb_uop_bits_br_mask <= arb_uop_bits_br_mask & ~io_brupdate_b1_resolve_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, generators/boom/src/main/scala/v4/util/util.scala:93:{25,27}
    end
    else begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:536:23
      arb_uop_valid <=
        io_iss_uop_valid
        & ~((|(io_brupdate_b1_mispredict_mask & io_iss_uop_bits_br_mask)) | io_kill);	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :93:{37,40}, generators/boom/src/main/scala/v4/util/util.scala:61:61, :126:{51,59}
      arb_uop_bits_is_rvc <= io_iss_uop_bits_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_fu_code_0 <= io_iss_uop_bits_fu_code_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_br_mask <= io_iss_uop_bits_br_mask & ~io_brupdate_b1_resolve_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, generators/boom/src/main/scala/v4/util/util.scala:93:{25,27}
      arb_uop_bits_br_tag <= io_iss_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_br_type <= io_iss_uop_bits_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_is_sfb <= io_iss_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_is_mov <= io_iss_uop_bits_is_mov;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_ftq_idx <= io_iss_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_edge_inst <= io_iss_uop_bits_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_pc_lob <= io_iss_uop_bits_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_taken <= io_iss_uop_bits_taken;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_imm_sel <= io_iss_uop_bits_imm_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_pimm <= io_iss_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_op1_sel <= io_iss_uop_bits_op1_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_op2_sel <= io_iss_uop_bits_op2_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_rob_idx <= io_iss_uop_bits_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_pdst <= io_iss_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_prs1 <= io_iss_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_prs2 <= io_iss_uop_bits_prs2;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_ppred <= io_iss_uop_bits_ppred;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_csr_cmd <= io_iss_uop_bits_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_ldst_is_rs1 <= io_iss_uop_bits_ldst_is_rs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_dst_rtype <= io_iss_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_lrs1_rtype <= io_iss_uop_bits_lrs1_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_lrs2_rtype <= io_iss_uop_bits_lrs2_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_fcn_dw <= io_iss_uop_bits_fcn_dw;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
      arb_uop_bits_fcn_op <= io_iss_uop_bits_fcn_op;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20
    end
    arb_uop_bits_iw_p1_bypass_hint <= ~_GEN & io_iss_uop_bits_iw_p1_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :94:17, :536:{23,40}, :540:36
    arb_uop_bits_iw_p2_bypass_hint <= ~_GEN & io_iss_uop_bits_iw_p2_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :94:17, :536:{23,40}, :540:36, :541:36
    rrd_uop_valid <= ~_GEN & arb_uop_valid & ~((|_will_replay_T) | io_kill);	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :94:17, :95:20, :96:{17,37}, :536:{23,40}, :540:36, :543:19, generators/boom/src/main/scala/v4/util/util.scala:61:61, :126:{51,59}
    rrd_uop_bits_is_rvc <= arb_uop_bits_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_fu_code_0 <= arb_uop_bits_fu_code_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_iw_p1_bypass_hint <= arb_uop_bits_iw_p1_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_iw_p2_bypass_hint <= arb_uop_bits_iw_p2_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_br_mask <= arb_uop_bits_br_mask & ~io_brupdate_b1_resolve_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20, generators/boom/src/main/scala/v4/util/util.scala:93:{25,27}
    rrd_uop_bits_br_tag <= arb_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_br_type <= arb_uop_bits_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_is_sfb <= arb_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_is_mov <= arb_uop_bits_is_mov;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_ftq_idx <= arb_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_edge_inst <= arb_uop_bits_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_pc_lob <= arb_uop_bits_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_taken <= arb_uop_bits_taken;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_imm_sel <= arb_uop_bits_imm_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_pimm <= arb_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_op1_sel <= arb_uop_bits_op1_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_op2_sel <= arb_uop_bits_op2_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_rob_idx <= arb_uop_bits_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_pdst <= arb_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_prs1 <= arb_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_prs2 <= arb_uop_bits_prs2;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_csr_cmd <= arb_uop_bits_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_ldst_is_rs1 <= arb_uop_bits_ldst_is_rs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_dst_rtype <= arb_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_lrs1_rtype <= arb_uop_bits_lrs1_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_lrs2_rtype <= arb_uop_bits_lrs2_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_fcn_dw <= arb_uop_bits_fcn_dw;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    rrd_uop_bits_fcn_op <= arb_uop_bits_fcn_op;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20
    exe_uop_valid <=
      rrd_uop_valid
      & ~((|(io_brupdate_b1_mispredict_mask & rrd_uop_bits_br_mask)) | io_kill);	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20, :99:{34,37}, generators/boom/src/main/scala/v4/util/util.scala:61:61, :126:{51,59}
    exe_uop_bits_is_rvc <= rrd_uop_bits_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_fu_code_0 <= rrd_uop_bits_fu_code_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_br_mask <= rrd_uop_bits_br_mask & ~io_brupdate_b1_resolve_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20, generators/boom/src/main/scala/v4/util/util.scala:93:{25,27}
    exe_uop_bits_br_tag <= rrd_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_br_type <= rrd_uop_bits_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_is_sfb <= rrd_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_is_mov <= rrd_uop_bits_is_mov;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_ftq_idx <= rrd_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_edge_inst <= rrd_uop_bits_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_pc_lob <= rrd_uop_bits_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_taken <= rrd_uop_bits_taken;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_pimm <= rrd_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_op1_sel <= rrd_uop_bits_op1_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_op2_sel <= rrd_uop_bits_op2_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_rob_idx <= rrd_uop_bits_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_ldq_idx <= io_rrd_brf_resp_ldq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    exe_uop_bits_stq_idx <= io_rrd_brf_resp_stq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    exe_uop_bits_pdst <= rrd_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_prs1 <= rrd_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_csr_cmd <= rrd_uop_bits_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_ldst_is_rs1 <= rrd_uop_bits_ldst_is_rs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_dst_rtype <= rrd_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_fcn_dw <= rrd_uop_bits_fcn_dw;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_uop_bits_fcn_op <= rrd_uop_bits_fcn_op;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :98:20
    exe_rs1_data <=
      (&rrd_uop_bits_lrs1_rtype)
        ? 64'h0
        : rs1_hit
            ? (hits_0 ? io_rrd_irf_bypasses_0_bits_data : 64'h0)
              | (hits_1 ? io_rrd_irf_bypasses_1_bits_data : 64'h0)
            : io_rrd_irf_resps_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :113:55, :114:{19,28}, :133:25, :137:{22,47}, :551:25, src/main/scala/chisel3/util/Mux.scala:30:73
    exe_rs2_data <=
      (&rrd_uop_bits_lrs2_rtype)
        ? 64'h0
        : rs2_hit
            ? (hits_0_1 ? io_rrd_irf_bypasses_0_bits_data : 64'h0)
              | (hits_1_1 ? io_rrd_irf_bypasses_1_bits_data : 64'h0)
            : io_rrd_irf_resps_1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :113:55, :114:{19,28}, :134:25, :142:{24,49}, :551:25, src/main/scala/chisel3/util/Mux.scala:30:73
    exe_pred_data <= io_rrd_prf_resp;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:186:26
    exe_imm_data <=
      _exe_imm_data_T
        ? {{59{rrd_uop_bits_pimm[4]}}, rrd_uop_bits_pimm}
        : {{33{exe_imm_data_ip[19]}},
           _exe_imm_data_i4_1_T ? exe_imm_data_ip[18:8] : {11{exe_imm_data_ip[19]}},
           _exe_imm_data_i4_1_T | _exe_imm_data_i11_T_1
             ? exe_imm_data_ip[7:0]
             : {8{exe_imm_data_ip[19]}},
           ~_exe_imm_data_i4_1_T
             & (_exe_imm_data_i11_T_1 | rrd_uop_bits_imm_sel == 3'h2
                  ? exe_imm_data_ip[8]
                  : exe_imm_data_ip[19]),
           _exe_imm_data_i4_1_T ? 5'h0 : exe_imm_data_ip[18:14],
           _exe_imm_data_i4_1_T ? 5'h0 : exe_imm_data_ip[13:9],
           (rrd_uop_bits_imm_sel == 3'h1 | rrd_uop_bits_imm_sel == 3'h0)
             & exe_imm_data_ip[8]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :170:{29,33}, generators/boom/src/main/scala/v4/util/util.scala:288:{20,25,46}, :301:17, :303:18, :304:{21,27,39}, :305:{21,36,44,56}, :306:21, :307:{21,36,44,56}, :308:{21,44}, :309:{21,44}, :310:{21,27,36,44}, generators/rocket-chip/src/main/scala/util/package.scala:16:47
    exe_ftq_data_0_entry_cfi_idx_valid <= io_rrd_ftq_resps_0_entry_cfi_idx_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    exe_ftq_data_0_entry_cfi_idx_bits <= io_rrd_ftq_resps_0_entry_cfi_idx_bits;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    exe_ftq_data_0_entry_start_bank <= io_rrd_ftq_resps_0_entry_start_bank;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    exe_ftq_data_0_pc <= io_rrd_ftq_resps_0_pc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    exe_ftq_data_1_valid <= io_rrd_ftq_resps_1_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    exe_ftq_data_1_pc <= io_rrd_ftq_resps_1_pc;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
      automatic logic [31:0] _RANDOM[0:54];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
        for (logic [5:0] i = 6'h0; i < 6'h37; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
        end	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
        arb_uop_valid = _RANDOM[6'h0][0];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_is_rvc = _RANDOM[6'h2][1];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_fu_code_0 = _RANDOM[6'h3][14];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_iw_p1_bypass_hint = _RANDOM[6'h3][29];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_iw_p2_bypass_hint = _RANDOM[6'h3][30];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_br_mask = _RANDOM[6'h4][8:1];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_br_tag = _RANDOM[6'h4][11:9];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_br_type = _RANDOM[6'h4][15:12];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_is_sfb = _RANDOM[6'h4][16];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_is_mov = _RANDOM[6'h4][24];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_ftq_idx = _RANDOM[6'h4][28:25];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_edge_inst = _RANDOM[6'h4][29];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_pc_lob = {_RANDOM[6'h4][31:30], _RANDOM[6'h5][3:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_taken = _RANDOM[6'h5][4];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_imm_sel = _RANDOM[6'h5][8:6];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_pimm = _RANDOM[6'h5][13:9];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_op1_sel = _RANDOM[6'h6][3:2];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_op2_sel = _RANDOM[6'h6][6:4];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_rob_idx = _RANDOM[6'h6][30:26];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_pdst = _RANDOM[6'h7][14:9];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_prs1 = _RANDOM[6'h7][20:15];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_prs2 = _RANDOM[6'h7][26:21];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_ppred = _RANDOM[6'h8][4:1];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_csr_cmd = _RANDOM[6'hA][30:28];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_ldst_is_rs1 = _RANDOM[6'hA][31];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_dst_rtype = _RANDOM[6'hB][25:24];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_lrs1_rtype = _RANDOM[6'hB][27:26];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_lrs2_rtype = _RANDOM[6'hB][29:28];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_fcn_dw = _RANDOM[6'hB][31];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        arb_uop_bits_fcn_op = _RANDOM[6'hC][4:0];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
        rrd_uop_valid = _RANDOM[6'hC][22];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :95:20, :492:7
        rrd_uop_bits_is_rvc = _RANDOM[6'hE][23];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_fu_code_0 = _RANDOM[6'h10][4];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_iw_p1_bypass_hint = _RANDOM[6'h10][19];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_iw_p2_bypass_hint = _RANDOM[6'h10][20];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_br_mask = _RANDOM[6'h10][30:23];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_br_tag = {_RANDOM[6'h10][31], _RANDOM[6'h11][1:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_br_type = _RANDOM[6'h11][5:2];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_is_sfb = _RANDOM[6'h11][6];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_is_mov = _RANDOM[6'h11][14];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_ftq_idx = _RANDOM[6'h11][18:15];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_edge_inst = _RANDOM[6'h11][19];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_pc_lob = _RANDOM[6'h11][25:20];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_taken = _RANDOM[6'h11][26];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_imm_sel = _RANDOM[6'h11][30:28];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_pimm = {_RANDOM[6'h11][31], _RANDOM[6'h12][3:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_op1_sel = _RANDOM[6'h12][25:24];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_op2_sel = _RANDOM[6'h12][28:26];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_rob_idx = _RANDOM[6'h13][20:16];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_pdst = {_RANDOM[6'h13][31], _RANDOM[6'h14][4:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_prs1 = _RANDOM[6'h14][10:5];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_prs2 = _RANDOM[6'h14][16:11];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_csr_cmd = _RANDOM[6'h17][20:18];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_ldst_is_rs1 = _RANDOM[6'h17][21];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_dst_rtype = _RANDOM[6'h18][15:14];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_lrs1_rtype = _RANDOM[6'h18][17:16];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_lrs2_rtype = _RANDOM[6'h18][19:18];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_fcn_dw = _RANDOM[6'h18][21];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        rrd_uop_bits_fcn_op = _RANDOM[6'h18][26:22];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
        exe_uop_valid = _RANDOM[6'h19][12];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_is_rvc = _RANDOM[6'h1B][13];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_fu_code_0 = _RANDOM[6'h1C][26];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_br_mask = _RANDOM[6'h1D][20:13];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_br_tag = _RANDOM[6'h1D][23:21];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_br_type = _RANDOM[6'h1D][27:24];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_is_sfb = _RANDOM[6'h1D][28];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_is_mov = _RANDOM[6'h1E][4];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_ftq_idx = _RANDOM[6'h1E][8:5];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_edge_inst = _RANDOM[6'h1E][9];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_pc_lob = _RANDOM[6'h1E][15:10];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_taken = _RANDOM[6'h1E][16];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_pimm = _RANDOM[6'h1E][25:21];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_op1_sel = _RANDOM[6'h1F][15:14];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_op2_sel = _RANDOM[6'h1F][18:16];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_rob_idx = _RANDOM[6'h20][10:6];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_ldq_idx = _RANDOM[6'h20][14:11];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_stq_idx = _RANDOM[6'h20][18:15];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_pdst = _RANDOM[6'h20][26:21];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_prs1 = {_RANDOM[6'h20][31:27], _RANDOM[6'h21][0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_csr_cmd = _RANDOM[6'h24][10:8];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_ldst_is_rs1 = _RANDOM[6'h24][11];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_dst_rtype = _RANDOM[6'h25][5:4];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_fcn_dw = _RANDOM[6'h25][11];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_uop_bits_fcn_op = _RANDOM[6'h25][16:12];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :492:7
        exe_rs1_data = {_RANDOM[6'h26][31:2], _RANDOM[6'h27], _RANDOM[6'h28][1:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:133:25, :492:7
        exe_rs2_data = {_RANDOM[6'h28][31:2], _RANDOM[6'h29], _RANDOM[6'h2A][1:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:133:25, :134:25, :492:7
        exe_pred_data = _RANDOM[6'h2A][2];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:134:25, :186:26, :492:7
        exe_imm_data = {_RANDOM[6'h2A][31:3], _RANDOM[6'h2B], _RANDOM[6'h2C][2:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:134:25, :170:29, :492:7
        exe_ftq_data_0_entry_cfi_idx_valid = _RANDOM[6'h2C][4];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:170:29, :251:25, :492:7
        exe_ftq_data_0_entry_cfi_idx_bits = _RANDOM[6'h2C][6:5];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:170:29, :251:25, :492:7
        exe_ftq_data_0_entry_start_bank = _RANDOM[6'h2E][0];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25, :492:7
        exe_ftq_data_0_pc = {_RANDOM[6'h30][31:9], _RANDOM[6'h31][16:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25, :492:7
        exe_ftq_data_1_valid = _RANDOM[6'h31][17];	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25, :492:7
        exe_ftq_data_1_pc = {_RANDOM[6'h35][31:23], _RANDOM[6'h36][30:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25, :492:7
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ALUUnit alu (	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:558:19
    .io_req_valid                               (exe_uop_valid & exe_uop_bits_fu_code_0),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20, :559:38
    .io_req_bits_uop_is_rvc                     (exe_uop_bits_is_rvc),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_br_mask                    (exe_uop_bits_br_mask),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_br_tag                     (exe_uop_bits_br_tag),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_br_type                    (exe_uop_bits_br_type),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_is_sfb                     (exe_uop_bits_is_sfb),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_is_mov                     (exe_uop_bits_is_mov),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_ftq_idx                    (exe_uop_bits_ftq_idx),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_edge_inst                  (exe_uop_bits_edge_inst),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_pc_lob                     (exe_uop_bits_pc_lob),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_taken                      (exe_uop_bits_taken),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_pimm                       (exe_uop_bits_pimm),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_op1_sel                    (exe_uop_bits_op1_sel),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_op2_sel                    (exe_uop_bits_op2_sel),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_rob_idx                    (exe_uop_bits_rob_idx),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_ldq_idx                    (exe_uop_bits_ldq_idx),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_stq_idx                    (exe_uop_bits_stq_idx),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_pdst                       (exe_uop_bits_pdst),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_prs1                       (exe_uop_bits_prs1),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_csr_cmd                    (exe_uop_bits_csr_cmd),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_ldst_is_rs1                (exe_uop_bits_ldst_is_rs1),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_dst_rtype                  (exe_uop_bits_dst_rtype),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_fcn_dw                     (exe_uop_bits_fcn_dw),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_uop_fcn_op                     (exe_uop_bits_fcn_op),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:98:20
    .io_req_bits_rs1_data                       (exe_rs1_data),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:133:25
    .io_req_bits_rs2_data                       (exe_rs2_data),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:134:25
    .io_req_bits_ftq_info_0_entry_cfi_idx_valid (exe_ftq_data_0_entry_cfi_idx_valid),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    .io_req_bits_ftq_info_0_entry_cfi_idx_bits  (exe_ftq_data_0_entry_cfi_idx_bits),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    .io_req_bits_ftq_info_0_entry_start_bank    (exe_ftq_data_0_entry_start_bank),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    .io_req_bits_ftq_info_0_pc                  (exe_ftq_data_0_pc),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    .io_req_bits_ftq_info_1_valid               (exe_ftq_data_1_valid),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    .io_req_bits_ftq_info_1_pc                  (exe_ftq_data_1_pc),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:251:25
    .io_req_bits_pred_data                      (exe_pred_data),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:186:26
    .io_req_bits_imm_data                       (exe_imm_data),	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:170:29
    .io_resp_valid                              (io_alu_resp_valid),
    .io_resp_bits_uop_br_mask                   (io_alu_resp_bits_uop_br_mask),
    .io_resp_bits_uop_br_type                   (io_alu_resp_bits_uop_br_type),
    .io_resp_bits_uop_is_sfb                    (io_alu_resp_bits_uop_is_sfb),
    .io_resp_bits_uop_rob_idx                   (io_alu_resp_bits_uop_rob_idx),
    .io_resp_bits_uop_pdst                      (io_alu_resp_bits_uop_pdst),
    .io_resp_bits_uop_csr_cmd                   (/* unused */),
    .io_resp_bits_uop_dst_rtype                 (io_alu_resp_bits_uop_dst_rtype),
    .io_resp_bits_data                          (io_alu_resp_bits_data),
    .io_resp_bits_predicated                    (io_alu_resp_bits_predicated),
    .io_brinfo_valid                            (io_brinfo_valid),
    .io_brinfo_bits_uop_is_rvc                  (io_brinfo_bits_uop_is_rvc),
    .io_brinfo_bits_uop_br_mask                 (io_brinfo_bits_uop_br_mask),
    .io_brinfo_bits_uop_br_tag                  (io_brinfo_bits_uop_br_tag),
    .io_brinfo_bits_uop_ftq_idx                 (io_brinfo_bits_uop_ftq_idx),
    .io_brinfo_bits_uop_edge_inst               (io_brinfo_bits_uop_edge_inst),
    .io_brinfo_bits_uop_pc_lob                  (io_brinfo_bits_uop_pc_lob),
    .io_brinfo_bits_uop_rob_idx                 (io_brinfo_bits_uop_rob_idx),
    .io_brinfo_bits_uop_ldq_idx                 (io_brinfo_bits_uop_ldq_idx),
    .io_brinfo_bits_uop_stq_idx                 (io_brinfo_bits_uop_stq_idx),
    .io_brinfo_bits_mispredict                  (io_brinfo_bits_mispredict),
    .io_brinfo_bits_taken                       (io_brinfo_bits_taken),
    .io_brinfo_bits_cfi_type                    (io_brinfo_bits_cfi_type),
    .io_brinfo_bits_pc_sel                      (io_brinfo_bits_pc_sel),
    .io_brinfo_bits_jalr_target                 (io_brinfo_bits_jalr_target),
    .io_brinfo_bits_target_offset               (io_brinfo_bits_target_offset)
  );
  assign io_arb_irf_reqs_0_valid =
    arb_uop_valid & _arb_rebusied_prs1_T & ~arb_uop_bits_iw_p1_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :121:{72,83,86}, :492:7
  assign io_arb_irf_reqs_0_bits = arb_uop_bits_prs1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
  assign io_arb_irf_reqs_1_valid =
    arb_uop_valid & _arb_rebusied_prs2_T & ~arb_uop_bits_iw_p2_bypass_hint;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :125:{74,85,88}, :492:7
  assign io_arb_irf_reqs_1_bits = arb_uop_bits_prs2;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
  assign io_arb_prf_req_bits = arb_uop_bits_ppred;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
  assign io_arb_immrf_req_bits = arb_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
  assign io_rrd_immrf_wakeup_valid =
    rrd_uop_valid & ~(_exe_imm_data_ip_T | _exe_imm_data_T);	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :162:47, :163:5, :492:7, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59
  assign io_rrd_immrf_wakeup_bits_uop_pimm = rrd_uop_bits_pimm;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
  assign io_arb_brf_req_bits = arb_uop_bits_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
  assign io_arb_ftq_reqs_0_valid = io_arb_ftq_reqs_0_valid_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:244:45, :492:7
  assign io_arb_ftq_reqs_0_bits = arb_uop_bits_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7
  assign io_arb_ftq_reqs_1_valid = io_arb_ftq_reqs_1_valid_0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:248:45, :492:7
  assign io_arb_ftq_reqs_1_bits = arb_uop_bits_ftq_idx + 4'h1;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :492:7, generators/boom/src/main/scala/v4/util/util.scala:211:14
  assign io_fast_wakeup_valid = io_iss_uop_valid & io_iss_uop_bits_dst_rtype == 2'h0;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:121:72, :492:7, :505:22, :506:32
  assign io_fast_wakeup_bits_uop_pdst = io_iss_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
  assign io_fast_wakeup_bits_uop_dst_rtype = io_iss_uop_bits_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7
  assign io_fast_pred_wakeup_valid =
    rrd_uop_valid & (|rrd_uop_bits_br_type) & rrd_uop_bits_is_sfb;	// generators/boom/src/main/scala/v4/common/micro-op.scala:120:34, generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7, :514:49
  assign io_fast_pred_wakeup_bits_uop_pdst = rrd_uop_bits_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:95:20, :492:7
  assign io_squash_iss = _io_squash_iss_output;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:492:7, :525:77
  assign io_child_rebusy = arb_rebusied & arb_uop_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/execution-unit.scala:92:20, :130:45, :492:7, :530:22
endmodule

