// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ALUUnit(	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  input         io_req_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_req_bits_uop_is_rvc,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [7:0]  io_req_bits_uop_br_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [2:0]  io_req_bits_uop_br_tag,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [3:0]  io_req_bits_uop_br_type,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_uop_is_sfb,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_req_bits_uop_is_mov,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [3:0]  io_req_bits_uop_ftq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_uop_edge_inst,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [5:0]  io_req_bits_uop_pc_lob,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_uop_taken,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [4:0]  io_req_bits_uop_pimm,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [1:0]  io_req_bits_uop_op1_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [2:0]  io_req_bits_uop_op2_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [4:0]  io_req_bits_uop_rob_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [3:0]  io_req_bits_uop_ldq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_req_bits_uop_stq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [5:0]  io_req_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_req_bits_uop_prs1,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [2:0]  io_req_bits_uop_csr_cmd,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_uop_ldst_is_rs1,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [1:0]  io_req_bits_uop_dst_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_uop_fcn_dw,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [4:0]  io_req_bits_uop_fcn_op,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [63:0] io_req_bits_rs1_data,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_req_bits_rs2_data,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_ftq_info_0_entry_cfi_idx_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [1:0]  io_req_bits_ftq_info_0_entry_cfi_idx_bits,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_ftq_info_0_entry_start_bank,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [39:0] io_req_bits_ftq_info_0_pc,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_ftq_info_1_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [39:0] io_req_bits_ftq_info_1_pc,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input         io_req_bits_pred_data,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  input  [63:0] io_req_bits_imm_data,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output        io_resp_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [7:0]  io_resp_bits_uop_br_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [3:0]  io_resp_bits_uop_br_type,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output        io_resp_bits_uop_is_sfb,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [4:0]  io_resp_bits_uop_rob_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [5:0]  io_resp_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [2:0]  io_resp_bits_uop_csr_cmd,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [1:0]  io_resp_bits_uop_dst_rtype,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [63:0] io_resp_bits_data,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output        io_resp_bits_predicated,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_brinfo_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_brinfo_bits_uop_is_rvc,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [7:0]  io_brinfo_bits_uop_br_mask,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [2:0]  io_brinfo_bits_uop_br_tag,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [3:0]  io_brinfo_bits_uop_ftq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output        io_brinfo_bits_uop_edge_inst,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [5:0]  io_brinfo_bits_uop_pc_lob,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [4:0]  io_brinfo_bits_uop_rob_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [3:0]  io_brinfo_bits_uop_ldq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_brinfo_bits_uop_stq_idx,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output        io_brinfo_bits_mispredict,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
                io_brinfo_bits_taken,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [2:0]  io_brinfo_bits_cfi_type,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [1:0]  io_brinfo_bits_pc_sel,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [39:0] io_brinfo_bits_jalr_target,	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
  output [20:0] io_brinfo_bits_target_offset	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14
);

  wire [63:0]      _alu_io_out;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:173:19
  wire [39:0]      _uop_pc_T_2 =
    {io_req_bits_ftq_info_0_pc[39:6], io_req_bits_uop_pc_lob}
    - {38'h0, io_req_bits_uop_edge_inst, 1'h0};	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14, :120:29, :150:40
  wire [66:0]      op1_shl =
    {3'h0,
     io_req_bits_uop_fcn_dw ? io_req_bits_rs1_data : {32'h0, io_req_bits_rs1_data[31:0]}}
    << (io_req_bits_uop_fcn_op == 5'h0 ? io_req_bits_uop_pimm[2:1] : 2'h0);	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:151:{22,34,66}, :152:20, :153:{25,55}, :155:45, :164:45
  wire [3:0][63:0] _GEN =
    {{op1_shl[63:0]},
     {{{24{_uop_pc_T_2[39]}}, _uop_pc_T_2}},
     {64'h0},
     {io_req_bits_rs1_data}};	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:150:40, :153:55, :155:45, generators/boom/src/main/scala/v4/util/util.scala:288:{20,25,46}
  wire             br_eq = io_req_bits_rs1_data == io_req_bits_rs2_data;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:183:21
  wire             br_ltu = io_req_bits_rs1_data < io_req_bits_rs2_data;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:184:28
  wire             br_lt =
    (io_req_bits_rs1_data[63] ^ ~(io_req_bits_rs2_data[63])) & br_ltu
    | io_req_bits_rs1_data[63] & ~(io_req_bits_rs2_data[63]);	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:184:28, :185:{17,22,36,46,55}, :186:{29,31}
  wire [1:0]       pc_sel =
    io_req_bits_uop_br_type == 4'h8
      ? 2'h2
      : io_req_bits_uop_br_type == 4'h7
          ? 2'h1
          : {1'h0,
             io_req_bits_uop_br_type == 4'h6
               ? br_ltu
               : io_req_bits_uop_br_type == 4'h5
                   ? br_lt
                   : io_req_bits_uop_br_type == 4'h4
                       ? ~br_ltu
                       : io_req_bits_uop_br_type == 4'h3
                           ? ~br_lt
                           : io_req_bits_uop_br_type == 4'h2
                               ? br_eq
                               : io_req_bits_uop_br_type == 4'h1 & ~br_eq};	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:120:29, :150:45, :183:21, :184:28, :185:55, :188:48, :190:{37,38}, :192:38, :193:38
  wire             is_br =
    io_req_valid
    & (io_req_bits_uop_br_type == 4'h1 | io_req_bits_uop_br_type == 4'h2
       | io_req_bits_uop_br_type == 4'h3 | io_req_bits_uop_br_type == 4'h4
       | io_req_bits_uop_br_type == 4'h5 | io_req_bits_uop_br_type == 4'h6)
    & ~io_req_bits_uop_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:188:48, :225:{50,53}, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59
  wire             is_jalr = io_req_valid & io_req_bits_uop_br_type == 4'h8;	// generators/boom/src/main/scala/v4/common/micro-op.scala:119:34, generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:188:48, :227:37
  wire [63:0]      _jalr_target_xlen_T =
    io_req_bits_rs1_data + {{43{io_req_bits_imm_data[20]}}, io_req_bits_imm_data[20:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:208:33, :231:41
  wire [39:0]      jalr_target =
    {_jalr_target_xlen_T[63:39] == 25'h0 | (&(_jalr_target_xlen_T[63:39]))
       ? _jalr_target_xlen_T[39]
       : ~(_jalr_target_xlen_T[38]),
     _jalr_target_xlen_T[38:0]} & 40'hFFFFFFFFFE;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:215:23, :216:{18,21,29,34,46,59,62}, :217:{8,16}, :231:41, :232:{79,86}
  wire             brinfo_valid = is_br | is_jalr;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:225:50, :227:37, :237:15
  wire             _io_resp_bits_predicated_T = io_req_bits_uop_br_type == 4'h0;	// generators/boom/src/main/scala/v4/common/micro-op.scala:121:34, generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:188:48
  RocketALU alu (	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:173:19
    .io_dw  ((&io_req_bits_uop_op1_sel) | io_req_bits_uop_fcn_dw),	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:178:{20,33}
    .io_fn  (io_req_bits_uop_fcn_op),
    .io_in2
      (io_req_bits_uop_op2_sel == 3'h6 | io_req_bits_uop_op2_sel == 3'h5
         ? 64'h1
           << (io_req_bits_uop_op2_sel[0]
                 ? io_req_bits_rs2_data[5:0]
                 : io_req_bits_imm_data[5:0])
         : io_req_bits_uop_op2_sel == 3'h3
             ? {61'h0, io_req_bits_uop_is_rvc ? 3'h2 : 3'h4}
             : io_req_bits_uop_op2_sel == 3'h0
                 ? io_req_bits_rs2_data
                 : io_req_bits_uop_op2_sel == 3'h4
                     ? {59'h0, io_req_bits_uop_prs1[4:0]}
                     : io_req_bits_uop_op2_sel == 3'h1 ? io_req_bits_imm_data : 64'h0),	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:105:14, :155:45, :162:{28,40}, :164:45, :166:37, :168:20, src/main/scala/chisel3/util/OneHot.scala:58:35
    .io_in1 (_GEN[io_req_bits_uop_op1_sel]),	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:155:45
    .io_out (_alu_io_out)
  );
  assign io_resp_valid = io_req_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_br_mask = io_req_bits_uop_br_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_br_type = io_req_bits_uop_br_type;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_is_sfb = io_req_bits_uop_is_sfb;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_rob_idx = io_req_bits_uop_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_pdst = io_req_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_csr_cmd = io_req_bits_uop_csr_cmd;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_uop_dst_rtype = io_req_bits_uop_dst_rtype;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_resp_bits_data =
    (|io_req_bits_uop_br_type) & io_req_bits_uop_is_sfb
      ? {63'h0, pc_sel == 2'h1}
      : _io_resp_bits_predicated_T & io_req_bits_uop_is_sfb & io_req_bits_pred_data
          ? (io_req_bits_uop_ldst_is_rs1 ? io_req_bits_rs1_data : io_req_bits_rs2_data)
          : io_req_bits_uop_is_mov ? io_req_bits_rs2_data : _alu_io_out;	// generators/boom/src/main/scala/v4/common/micro-op.scala:120:42, :121:34, generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :173:19, :188:48, :190:37, :201:33, :285:{20,51}, :286:10, :287:10, :290:{27,62}, src/main/scala/chisel3/util/OneHot.scala:58:35
  assign io_resp_bits_predicated =
    _io_resp_bits_predicated_T & io_req_bits_uop_is_sfb & io_req_bits_pred_data;	// generators/boom/src/main/scala/v4/common/micro-op.scala:121:34, generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :291:60
  assign io_brinfo_valid = brinfo_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :237:15
  assign io_brinfo_bits_uop_is_rvc = io_req_bits_uop_is_rvc;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_br_mask = io_req_bits_uop_br_mask;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_br_tag = io_req_bits_uop_br_tag;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_ftq_idx = io_req_bits_uop_ftq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_edge_inst = io_req_bits_uop_edge_inst;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_pc_lob = io_req_bits_uop_pc_lob;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_rob_idx = io_req_bits_uop_rob_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_ldq_idx = io_req_bits_uop_ldq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_uop_stq_idx = io_req_bits_uop_stq_idx;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7
  assign io_brinfo_bits_mispredict =
    brinfo_valid
    & (pc_sel == 2'h2
         ? ~io_req_bits_ftq_info_1_valid | io_req_bits_ftq_info_1_pc != jalr_target
           | ~io_req_bits_ftq_info_0_entry_cfi_idx_valid
           | io_req_bits_ftq_info_0_entry_cfi_idx_bits != io_req_bits_uop_pc_lob[2:1]
         : pc_sel == 2'h1
             ? ~io_req_bits_uop_taken
             : pc_sel == 2'h0 & io_req_bits_uop_taken);	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :150:45, :155:45, :188:48, :190:37, :223:28, :232:{79,86}, :234:30, :237:{15,27}, :238:{18,32}, :239:18, :241:{18,32}, :242:{18,21}, :244:{18,31}, :245:{18,22}, :246:50, :247:{22,67}, :248:66
  assign io_brinfo_bits_taken = io_req_valid & (|io_req_bits_uop_br_type) & (|pc_sel);	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :188:48, :201:{33,42}, :202:28
  assign io_brinfo_bits_cfi_type = is_jalr ? 3'h3 : {2'h0, is_br};	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :155:45, :164:45, :225:50, :227:37, :258:36, :259:36
  assign io_brinfo_bits_pc_sel = pc_sel;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :188:48
  assign io_brinfo_bits_jalr_target = jalr_target;	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :232:{79,86}
  assign io_brinfo_bits_target_offset = io_req_bits_imm_data[20:0];	// generators/boom/src/main/scala/v4/exu/execution-units/functional-unit.scala:133:7, :208:33
endmodule

