// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module Arbiter2_BoomDCacheReqInternal(	// src/main/scala/chisel3/util/Arbiter.scala:133:7
  output        io_in_0_ready,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [31:0] io_in_0_bits_uop_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_debug_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_is_rvc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [39:0] io_in_0_bits_uop_debug_pc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_iq_type_0,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iq_type_1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iq_type_2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iq_type_3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_0,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_4,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_5,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_6,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_7,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_8,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fu_code_9,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_issued,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_issued_partial_agen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_issued_partial_dgen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_p1_speculative_child,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_p2_speculative_child,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_p1_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_p2_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_iw_p3_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_dis_col_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [7:0]  io_in_0_bits_uop_br_mask,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_0_bits_uop_br_tag,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_0_bits_uop_br_type,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_is_sfb,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_fence,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_fencei,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_sfence,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_amo,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_eret,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_sys_pc2epc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_rocc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_mov,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_0_bits_uop_ftq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_edge_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_0_bits_uop_pc_lob,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_taken,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_imm_rename,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_0_bits_uop_imm_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_0_bits_uop_pimm,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [19:0] io_in_0_bits_uop_imm_packed,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_0_bits_uop_op1_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_0_bits_uop_op2_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_fp_ctrl_ldst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_wen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_ren1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_ren2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_ren3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_swap12,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_swap23,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_0_bits_uop_fp_ctrl_typeTagIn,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_typeTagOut,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_fp_ctrl_fromint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_toint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_fastpipe,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_fma,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_div,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_sqrt,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_wflags,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fp_ctrl_vec,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_0_bits_uop_rob_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_0_bits_uop_ldq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_stq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_0_bits_uop_rxq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_0_bits_uop_pdst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_prs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_prs2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_prs3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_0_bits_uop_ppred,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_prs1_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_prs2_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_prs3_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_ppred_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_0_bits_uop_stale_pdst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_exception,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [63:0] io_in_0_bits_uop_exc_cause,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_0_bits_uop_mem_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_0_bits_uop_mem_size,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_mem_signed,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_uses_ldq,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_uses_stq,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_is_unique,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_flush_on_commit,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_0_bits_uop_csr_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_ldst_is_rs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_0_bits_uop_ldst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_lrs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_lrs2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_lrs3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_0_bits_uop_dst_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_lrs1_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_lrs2_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_frs3_en,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_fcn_dw,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_0_bits_uop_fcn_op,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_fp_val,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_0_bits_uop_fp_rm,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_0_bits_uop_fp_typ,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_uop_xcpt_pf_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_xcpt_ae_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_xcpt_ma_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_bp_debug_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_bp_xcpt_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_0_bits_uop_debug_fsrc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_0_bits_uop_debug_tsrc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [39:0] io_in_0_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_0_bits_is_hella,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_0_bits_way_en,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_0_bits_sdq_id,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_in_1_ready,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [31:0] io_in_1_bits_uop_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_debug_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_is_rvc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [39:0] io_in_1_bits_uop_debug_pc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_iq_type_0,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iq_type_1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iq_type_2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iq_type_3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_0,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_4,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_5,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_6,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_7,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_8,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fu_code_9,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_issued,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_issued_partial_agen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_issued_partial_dgen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_p1_speculative_child,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_p2_speculative_child,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_p1_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_p2_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_iw_p3_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_dis_col_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [7:0]  io_in_1_bits_uop_br_mask,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_1_bits_uop_br_tag,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_1_bits_uop_br_type,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_is_sfb,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_fence,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_fencei,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_sfence,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_amo,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_eret,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_sys_pc2epc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_rocc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_mov,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_1_bits_uop_ftq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_edge_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_1_bits_uop_pc_lob,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_taken,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_imm_rename,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_1_bits_uop_imm_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_1_bits_uop_pimm,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [19:0] io_in_1_bits_uop_imm_packed,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_1_bits_uop_op1_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_1_bits_uop_op2_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_fp_ctrl_ldst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_wen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_ren1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_ren2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_ren3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_swap12,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_swap23,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_1_bits_uop_fp_ctrl_typeTagIn,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_typeTagOut,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_fp_ctrl_fromint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_toint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_fastpipe,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_fma,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_div,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_sqrt,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_wflags,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fp_ctrl_vec,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_1_bits_uop_rob_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_1_bits_uop_ldq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_stq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_1_bits_uop_rxq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_1_bits_uop_pdst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_prs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_prs2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_prs3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_1_bits_uop_ppred,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_prs1_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_prs2_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_prs3_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_ppred_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_1_bits_uop_stale_pdst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_exception,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [63:0] io_in_1_bits_uop_exc_cause,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_1_bits_uop_mem_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_1_bits_uop_mem_size,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_mem_signed,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_uses_ldq,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_uses_stq,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_is_unique,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_flush_on_commit,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_1_bits_uop_csr_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_ldst_is_rs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [5:0]  io_in_1_bits_uop_ldst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_lrs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_lrs2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_lrs3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_1_bits_uop_dst_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_lrs1_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_lrs2_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_frs3_en,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_fcn_dw,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_1_bits_uop_fcn_op,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_fp_val,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_1_bits_uop_fp_rm,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [1:0]  io_in_1_bits_uop_fp_typ,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_uop_xcpt_pf_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_xcpt_ae_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_xcpt_ma_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_bp_debug_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_bp_xcpt_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [2:0]  io_in_1_bits_uop_debug_fsrc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_in_1_bits_uop_debug_tsrc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [39:0] io_in_1_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_in_1_bits_is_hella,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [3:0]  io_in_1_bits_way_en,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input  [4:0]  io_in_1_bits_sdq_id,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  input         io_out_ready,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_valid,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [31:0] io_out_bits_uop_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_debug_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_is_rvc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [39:0] io_out_bits_uop_debug_pc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_iq_type_0,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iq_type_1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iq_type_2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iq_type_3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_0,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_4,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_5,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_6,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_7,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_8,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fu_code_9,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_issued,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_issued_partial_agen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_issued_partial_dgen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_p1_speculative_child,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_p2_speculative_child,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_p1_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_p2_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_iw_p3_bypass_hint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_dis_col_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [7:0]  io_out_bits_uop_br_mask,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [2:0]  io_out_bits_uop_br_tag,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [3:0]  io_out_bits_uop_br_type,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_is_sfb,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_fence,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_fencei,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_sfence,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_amo,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_eret,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_sys_pc2epc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_rocc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_mov,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [3:0]  io_out_bits_uop_ftq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_edge_inst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [5:0]  io_out_bits_uop_pc_lob,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_taken,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_imm_rename,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [2:0]  io_out_bits_uop_imm_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [4:0]  io_out_bits_uop_pimm,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [19:0] io_out_bits_uop_imm_packed,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [1:0]  io_out_bits_uop_op1_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [2:0]  io_out_bits_uop_op2_sel,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_fp_ctrl_ldst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_wen,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_ren1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_ren2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_ren3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_swap12,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_swap23,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [1:0]  io_out_bits_uop_fp_ctrl_typeTagIn,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_typeTagOut,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_fp_ctrl_fromint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_toint,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_fastpipe,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_fma,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_div,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_sqrt,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_wflags,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fp_ctrl_vec,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [4:0]  io_out_bits_uop_rob_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [3:0]  io_out_bits_uop_ldq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_stq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [1:0]  io_out_bits_uop_rxq_idx,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [5:0]  io_out_bits_uop_pdst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_prs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_prs2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_prs3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [3:0]  io_out_bits_uop_ppred,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_prs1_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_prs2_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_prs3_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_ppred_busy,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [5:0]  io_out_bits_uop_stale_pdst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_exception,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [63:0] io_out_bits_uop_exc_cause,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [4:0]  io_out_bits_uop_mem_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [1:0]  io_out_bits_uop_mem_size,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_mem_signed,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_uses_ldq,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_uses_stq,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_is_unique,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_flush_on_commit,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [2:0]  io_out_bits_uop_csr_cmd,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_ldst_is_rs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [5:0]  io_out_bits_uop_ldst,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_lrs1,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_lrs2,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_lrs3,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [1:0]  io_out_bits_uop_dst_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_lrs1_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_lrs2_rtype,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_frs3_en,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_fcn_dw,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [4:0]  io_out_bits_uop_fcn_op,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_fp_val,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [2:0]  io_out_bits_uop_fp_rm,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [1:0]  io_out_bits_uop_fp_typ,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_uop_xcpt_pf_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_xcpt_ae_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_xcpt_ma_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_bp_debug_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_bp_xcpt_if,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [2:0]  io_out_bits_uop_debug_fsrc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
                io_out_bits_uop_debug_tsrc,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [39:0] io_out_bits_addr,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output        io_out_bits_is_hella,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [3:0]  io_out_bits_way_en,	// src/main/scala/chisel3/util/Arbiter.scala:140:14
  output [4:0]  io_out_bits_sdq_id	// src/main/scala/chisel3/util/Arbiter.scala:140:14
);

  assign io_in_0_ready = io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:133:7
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// src/main/scala/chisel3/util/Arbiter.scala:45:78, :133:7, :153:19
  assign io_out_valid = io_in_0_valid | io_in_1_valid;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :154:31
  assign io_out_bits_uop_inst =
    io_in_0_valid ? io_in_0_bits_uop_inst : io_in_1_bits_uop_inst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_debug_inst =
    io_in_0_valid ? io_in_0_bits_uop_debug_inst : io_in_1_bits_uop_debug_inst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_rvc =
    io_in_0_valid ? io_in_0_bits_uop_is_rvc : io_in_1_bits_uop_is_rvc;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_debug_pc =
    io_in_0_valid ? io_in_0_bits_uop_debug_pc : io_in_1_bits_uop_debug_pc;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iq_type_0 =
    io_in_0_valid ? io_in_0_bits_uop_iq_type_0 : io_in_1_bits_uop_iq_type_0;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iq_type_1 =
    io_in_0_valid ? io_in_0_bits_uop_iq_type_1 : io_in_1_bits_uop_iq_type_1;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iq_type_2 =
    io_in_0_valid ? io_in_0_bits_uop_iq_type_2 : io_in_1_bits_uop_iq_type_2;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iq_type_3 =
    io_in_0_valid ? io_in_0_bits_uop_iq_type_3 : io_in_1_bits_uop_iq_type_3;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_0 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_0 : io_in_1_bits_uop_fu_code_0;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_1 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_1 : io_in_1_bits_uop_fu_code_1;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_2 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_2 : io_in_1_bits_uop_fu_code_2;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_3 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_3 : io_in_1_bits_uop_fu_code_3;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_4 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_4 : io_in_1_bits_uop_fu_code_4;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_5 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_5 : io_in_1_bits_uop_fu_code_5;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_6 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_6 : io_in_1_bits_uop_fu_code_6;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_7 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_7 : io_in_1_bits_uop_fu_code_7;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_8 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_8 : io_in_1_bits_uop_fu_code_8;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fu_code_9 =
    io_in_0_valid ? io_in_0_bits_uop_fu_code_9 : io_in_1_bits_uop_fu_code_9;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_issued =
    io_in_0_valid ? io_in_0_bits_uop_iw_issued : io_in_1_bits_uop_iw_issued;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_issued_partial_agen =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_issued_partial_agen
      : io_in_1_bits_uop_iw_issued_partial_agen;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_issued_partial_dgen =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_issued_partial_dgen
      : io_in_1_bits_uop_iw_issued_partial_dgen;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_p1_speculative_child =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_p1_speculative_child
      : io_in_1_bits_uop_iw_p1_speculative_child;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_p2_speculative_child =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_p2_speculative_child
      : io_in_1_bits_uop_iw_p2_speculative_child;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_p1_bypass_hint =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_p1_bypass_hint
      : io_in_1_bits_uop_iw_p1_bypass_hint;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_p2_bypass_hint =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_p2_bypass_hint
      : io_in_1_bits_uop_iw_p2_bypass_hint;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_iw_p3_bypass_hint =
    io_in_0_valid
      ? io_in_0_bits_uop_iw_p3_bypass_hint
      : io_in_1_bits_uop_iw_p3_bypass_hint;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_dis_col_sel =
    io_in_0_valid ? io_in_0_bits_uop_dis_col_sel : io_in_1_bits_uop_dis_col_sel;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_br_mask =
    io_in_0_valid ? io_in_0_bits_uop_br_mask : io_in_1_bits_uop_br_mask;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_br_tag =
    io_in_0_valid ? io_in_0_bits_uop_br_tag : io_in_1_bits_uop_br_tag;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_br_type =
    io_in_0_valid ? io_in_0_bits_uop_br_type : io_in_1_bits_uop_br_type;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_sfb =
    io_in_0_valid ? io_in_0_bits_uop_is_sfb : io_in_1_bits_uop_is_sfb;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_fence =
    io_in_0_valid ? io_in_0_bits_uop_is_fence : io_in_1_bits_uop_is_fence;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_fencei =
    io_in_0_valid ? io_in_0_bits_uop_is_fencei : io_in_1_bits_uop_is_fencei;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_sfence =
    io_in_0_valid ? io_in_0_bits_uop_is_sfence : io_in_1_bits_uop_is_sfence;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_amo =
    io_in_0_valid ? io_in_0_bits_uop_is_amo : io_in_1_bits_uop_is_amo;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_eret =
    io_in_0_valid ? io_in_0_bits_uop_is_eret : io_in_1_bits_uop_is_eret;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_sys_pc2epc =
    io_in_0_valid ? io_in_0_bits_uop_is_sys_pc2epc : io_in_1_bits_uop_is_sys_pc2epc;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_rocc =
    io_in_0_valid ? io_in_0_bits_uop_is_rocc : io_in_1_bits_uop_is_rocc;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_mov =
    io_in_0_valid ? io_in_0_bits_uop_is_mov : io_in_1_bits_uop_is_mov;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_ftq_idx =
    io_in_0_valid ? io_in_0_bits_uop_ftq_idx : io_in_1_bits_uop_ftq_idx;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_edge_inst =
    io_in_0_valid ? io_in_0_bits_uop_edge_inst : io_in_1_bits_uop_edge_inst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_pc_lob =
    io_in_0_valid ? io_in_0_bits_uop_pc_lob : io_in_1_bits_uop_pc_lob;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_taken =
    io_in_0_valid ? io_in_0_bits_uop_taken : io_in_1_bits_uop_taken;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_imm_rename =
    io_in_0_valid ? io_in_0_bits_uop_imm_rename : io_in_1_bits_uop_imm_rename;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_imm_sel =
    io_in_0_valid ? io_in_0_bits_uop_imm_sel : io_in_1_bits_uop_imm_sel;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_pimm =
    io_in_0_valid ? io_in_0_bits_uop_pimm : io_in_1_bits_uop_pimm;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_imm_packed =
    io_in_0_valid ? io_in_0_bits_uop_imm_packed : io_in_1_bits_uop_imm_packed;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_op1_sel =
    io_in_0_valid ? io_in_0_bits_uop_op1_sel : io_in_1_bits_uop_op1_sel;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_op2_sel =
    io_in_0_valid ? io_in_0_bits_uop_op2_sel : io_in_1_bits_uop_op2_sel;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_ldst =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_ldst : io_in_1_bits_uop_fp_ctrl_ldst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_wen =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_wen : io_in_1_bits_uop_fp_ctrl_wen;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_ren1 =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_ren1 : io_in_1_bits_uop_fp_ctrl_ren1;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_ren2 =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_ren2 : io_in_1_bits_uop_fp_ctrl_ren2;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_ren3 =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_ren3 : io_in_1_bits_uop_fp_ctrl_ren3;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_swap12 =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_swap12 : io_in_1_bits_uop_fp_ctrl_swap12;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_swap23 =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_swap23 : io_in_1_bits_uop_fp_ctrl_swap23;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_typeTagIn =
    io_in_0_valid
      ? io_in_0_bits_uop_fp_ctrl_typeTagIn
      : io_in_1_bits_uop_fp_ctrl_typeTagIn;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_typeTagOut =
    io_in_0_valid
      ? io_in_0_bits_uop_fp_ctrl_typeTagOut
      : io_in_1_bits_uop_fp_ctrl_typeTagOut;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_fromint =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_fromint : io_in_1_bits_uop_fp_ctrl_fromint;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_toint =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_toint : io_in_1_bits_uop_fp_ctrl_toint;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_fastpipe =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_fastpipe : io_in_1_bits_uop_fp_ctrl_fastpipe;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_fma =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_fma : io_in_1_bits_uop_fp_ctrl_fma;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_div =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_div : io_in_1_bits_uop_fp_ctrl_div;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_sqrt =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_sqrt : io_in_1_bits_uop_fp_ctrl_sqrt;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_wflags =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_wflags : io_in_1_bits_uop_fp_ctrl_wflags;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_ctrl_vec =
    io_in_0_valid ? io_in_0_bits_uop_fp_ctrl_vec : io_in_1_bits_uop_fp_ctrl_vec;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_rob_idx =
    io_in_0_valid ? io_in_0_bits_uop_rob_idx : io_in_1_bits_uop_rob_idx;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_ldq_idx =
    io_in_0_valid ? io_in_0_bits_uop_ldq_idx : io_in_1_bits_uop_ldq_idx;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_stq_idx =
    io_in_0_valid ? io_in_0_bits_uop_stq_idx : io_in_1_bits_uop_stq_idx;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_rxq_idx =
    io_in_0_valid ? io_in_0_bits_uop_rxq_idx : io_in_1_bits_uop_rxq_idx;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_pdst =
    io_in_0_valid ? io_in_0_bits_uop_pdst : io_in_1_bits_uop_pdst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_prs1 =
    io_in_0_valid ? io_in_0_bits_uop_prs1 : io_in_1_bits_uop_prs1;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_prs2 =
    io_in_0_valid ? io_in_0_bits_uop_prs2 : io_in_1_bits_uop_prs2;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_prs3 =
    io_in_0_valid ? io_in_0_bits_uop_prs3 : io_in_1_bits_uop_prs3;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_ppred =
    io_in_0_valid ? io_in_0_bits_uop_ppred : io_in_1_bits_uop_ppred;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_prs1_busy =
    io_in_0_valid ? io_in_0_bits_uop_prs1_busy : io_in_1_bits_uop_prs1_busy;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_prs2_busy =
    io_in_0_valid ? io_in_0_bits_uop_prs2_busy : io_in_1_bits_uop_prs2_busy;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_prs3_busy =
    io_in_0_valid ? io_in_0_bits_uop_prs3_busy : io_in_1_bits_uop_prs3_busy;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_ppred_busy =
    io_in_0_valid ? io_in_0_bits_uop_ppred_busy : io_in_1_bits_uop_ppred_busy;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_stale_pdst =
    io_in_0_valid ? io_in_0_bits_uop_stale_pdst : io_in_1_bits_uop_stale_pdst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_exception =
    io_in_0_valid ? io_in_0_bits_uop_exception : io_in_1_bits_uop_exception;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_exc_cause =
    io_in_0_valid ? io_in_0_bits_uop_exc_cause : io_in_1_bits_uop_exc_cause;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_mem_cmd =
    io_in_0_valid ? io_in_0_bits_uop_mem_cmd : io_in_1_bits_uop_mem_cmd;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_mem_size =
    io_in_0_valid ? io_in_0_bits_uop_mem_size : io_in_1_bits_uop_mem_size;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_mem_signed =
    io_in_0_valid ? io_in_0_bits_uop_mem_signed : io_in_1_bits_uop_mem_signed;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_uses_ldq =
    io_in_0_valid ? io_in_0_bits_uop_uses_ldq : io_in_1_bits_uop_uses_ldq;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_uses_stq =
    io_in_0_valid ? io_in_0_bits_uop_uses_stq : io_in_1_bits_uop_uses_stq;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_is_unique =
    io_in_0_valid ? io_in_0_bits_uop_is_unique : io_in_1_bits_uop_is_unique;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_flush_on_commit =
    io_in_0_valid ? io_in_0_bits_uop_flush_on_commit : io_in_1_bits_uop_flush_on_commit;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_csr_cmd =
    io_in_0_valid ? io_in_0_bits_uop_csr_cmd : io_in_1_bits_uop_csr_cmd;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_ldst_is_rs1 =
    io_in_0_valid ? io_in_0_bits_uop_ldst_is_rs1 : io_in_1_bits_uop_ldst_is_rs1;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_ldst =
    io_in_0_valid ? io_in_0_bits_uop_ldst : io_in_1_bits_uop_ldst;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_lrs1 =
    io_in_0_valid ? io_in_0_bits_uop_lrs1 : io_in_1_bits_uop_lrs1;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_lrs2 =
    io_in_0_valid ? io_in_0_bits_uop_lrs2 : io_in_1_bits_uop_lrs2;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_lrs3 =
    io_in_0_valid ? io_in_0_bits_uop_lrs3 : io_in_1_bits_uop_lrs3;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_dst_rtype =
    io_in_0_valid ? io_in_0_bits_uop_dst_rtype : io_in_1_bits_uop_dst_rtype;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_lrs1_rtype =
    io_in_0_valid ? io_in_0_bits_uop_lrs1_rtype : io_in_1_bits_uop_lrs1_rtype;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_lrs2_rtype =
    io_in_0_valid ? io_in_0_bits_uop_lrs2_rtype : io_in_1_bits_uop_lrs2_rtype;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_frs3_en =
    io_in_0_valid ? io_in_0_bits_uop_frs3_en : io_in_1_bits_uop_frs3_en;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fcn_dw =
    io_in_0_valid ? io_in_0_bits_uop_fcn_dw : io_in_1_bits_uop_fcn_dw;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fcn_op =
    io_in_0_valid ? io_in_0_bits_uop_fcn_op : io_in_1_bits_uop_fcn_op;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_val =
    io_in_0_valid ? io_in_0_bits_uop_fp_val : io_in_1_bits_uop_fp_val;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_rm =
    io_in_0_valid ? io_in_0_bits_uop_fp_rm : io_in_1_bits_uop_fp_rm;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_fp_typ =
    io_in_0_valid ? io_in_0_bits_uop_fp_typ : io_in_1_bits_uop_fp_typ;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_xcpt_pf_if =
    io_in_0_valid ? io_in_0_bits_uop_xcpt_pf_if : io_in_1_bits_uop_xcpt_pf_if;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_xcpt_ae_if =
    io_in_0_valid ? io_in_0_bits_uop_xcpt_ae_if : io_in_1_bits_uop_xcpt_ae_if;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_xcpt_ma_if =
    io_in_0_valid ? io_in_0_bits_uop_xcpt_ma_if : io_in_1_bits_uop_xcpt_ma_if;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_bp_debug_if =
    io_in_0_valid ? io_in_0_bits_uop_bp_debug_if : io_in_1_bits_uop_bp_debug_if;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_bp_xcpt_if =
    io_in_0_valid ? io_in_0_bits_uop_bp_xcpt_if : io_in_1_bits_uop_bp_xcpt_if;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_debug_fsrc =
    io_in_0_valid ? io_in_0_bits_uop_debug_fsrc : io_in_1_bits_uop_debug_fsrc;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_uop_debug_tsrc =
    io_in_0_valid ? io_in_0_bits_uop_debug_tsrc : io_in_1_bits_uop_debug_tsrc;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_addr = io_in_0_valid ? io_in_0_bits_addr : io_in_1_bits_addr;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_is_hella =
    io_in_0_valid ? io_in_0_bits_is_hella : io_in_1_bits_is_hella;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_way_en = io_in_0_valid ? io_in_0_bits_way_en : io_in_1_bits_way_en;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
  assign io_out_bits_sdq_id = io_in_0_valid ? io_in_0_bits_sdq_id : io_in_1_bits_sdq_id;	// src/main/scala/chisel3/util/Arbiter.scala:133:7, :143:15, :145:26, :147:19
endmodule

