// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BankedRF(	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:54:7
  input         clock,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:54:7
                reset,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:54:7
                io_arb_read_reqs_0_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_arb_read_reqs_0_bits,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_arb_read_reqs_1_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_arb_read_reqs_1_bits,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  output        io_arb_read_reqs_2_ready,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_arb_read_reqs_2_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_arb_read_reqs_2_bits,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  output [64:0] io_rrd_read_resps_0,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
                io_rrd_read_resps_1,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
                io_rrd_read_resps_2,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_write_ports_0_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_write_ports_0_bits_addr,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [64:0] io_write_ports_0_bits_data,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_write_ports_1_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_write_ports_1_bits_addr,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [64:0] io_write_ports_1_bits_data	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
);

  `ifndef SYNTHESIS	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
    always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
      if (~reset
          & ~(~io_write_ports_0_valid | ~io_write_ports_1_valid
              | io_write_ports_0_bits_addr != io_write_ports_1_bits_addr)) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,16}, :46:{16,41}, :47:45
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
          $fatal;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  PartiallyPortedRF rfs_0 (	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:78:49
    .clock                      (clock),
    .reset                      (reset),
    .io_arb_read_reqs_0_valid   (io_arb_read_reqs_0_valid),
    .io_arb_read_reqs_0_bits    (io_arb_read_reqs_0_bits),
    .io_arb_read_reqs_1_valid   (io_arb_read_reqs_1_valid),
    .io_arb_read_reqs_1_bits    (io_arb_read_reqs_1_bits),
    .io_arb_read_reqs_2_ready   (io_arb_read_reqs_2_ready),
    .io_arb_read_reqs_2_valid   (io_arb_read_reqs_2_valid),
    .io_arb_read_reqs_2_bits    (io_arb_read_reqs_2_bits),
    .io_rrd_read_resps_0        (io_rrd_read_resps_0),
    .io_rrd_read_resps_1        (io_rrd_read_resps_1),
    .io_rrd_read_resps_2        (io_rrd_read_resps_2),
    .io_write_ports_0_valid     (io_write_ports_0_valid),
    .io_write_ports_0_bits_addr (io_write_ports_0_bits_addr),
    .io_write_ports_0_bits_data (io_write_ports_0_bits_data),
    .io_write_ports_1_valid     (io_write_ports_1_valid),
    .io_write_ports_1_bits_addr (io_write_ports_1_bits_addr),
    .io_write_ports_1_bits_data (io_write_ports_1_bits_data)
  );
endmodule

