// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module BranchMaskGenerationLogic(	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
  input        clock,	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
               reset,	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
               io_is_branch_0,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
               io_will_fire_0,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
  output [2:0] io_br_tag_0,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
  output [7:0] io_br_mask_0,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
  output       io_is_full_0,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
  input  [7:0] io_brupdate_b1_resolve_mask,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
               io_brupdate_b2_uop_br_mask,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
  input        io_brupdate_b2_mispredict,	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
               io_flush_pipeline	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
);

  reg [7:0] branch_mask;	// generators/boom/src/main/scala/v4/exu/decode.scala:756:28
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
    if (reset)	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
      branch_mask <= 8'h0;	// generators/boom/src/main/scala/v4/exu/decode.scala:756:28
    else if (io_flush_pipeline)	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
      branch_mask <= 8'h0;	// generators/boom/src/main/scala/v4/exu/decode.scala:756:28
    else	// generators/boom/src/main/scala/v4/exu/decode.scala:734:14
      branch_mask <=
        ({8{io_will_fire_0}}
         & (branch_mask[0]
              ? (branch_mask[1]
                   ? (branch_mask[2]
                        ? (branch_mask[3]
                             ? (branch_mask[4]
                                  ? (branch_mask[5]
                                       ? (branch_mask[6]
                                            ? {~(branch_mask[7]), 7'h0}
                                            : 8'h40)
                                       : 8'h20)
                                  : 8'h10)
                             : 8'h8)
                        : 8'h4)
                   : 8'h2)
              : 8'h1) | branch_mask) & ~io_brupdate_b1_resolve_mask
        & (io_brupdate_b2_mispredict ? io_brupdate_b2_uop_br_mask : 8'hFF);	// generators/boom/src/main/scala/v4/exu/decode.scala:756:28, :766:41, :771:18, :774:{13,27,32}, :776:{22,30}, :791:20, :800:19, :803:57, generators/boom/src/main/scala/v4/util/util.scala:97:23
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
      automatic logic [31:0] _RANDOM[0:0];	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
        branch_mask = _RANDOM[/*Zero width*/ 1'b0][7:0];	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7, :756:28
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_br_tag_0 =
    branch_mask[0]
      ? (branch_mask[1]
           ? (branch_mask[2]
                ? (branch_mask[3]
                     ? (branch_mask[4]
                          ? (branch_mask[5]
                               ? (branch_mask[6] ? {3{~(branch_mask[7])}} : 3'h6)
                               : 3'h5)
                          : 3'h4)
                     : 3'h3)
                : 3'h2)
           : 3'h1)
      : 3'h0;	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7, :756:28, :770:16, :774:{13,27,32}, :775:20
  assign io_br_mask_0 = branch_mask & ~io_brupdate_b1_resolve_mask;	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7, :756:28, generators/boom/src/main/scala/v4/util/util.scala:97:{21,23}
  assign io_is_full_0 = (&branch_mask) & io_is_branch_0;	// generators/boom/src/main/scala/v4/exu/decode.scala:732:7, :756:28, :766:{37,63}
endmodule

