// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module FPU(	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
  input         clock,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
                reset,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
                io_req_valid,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_ren2,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_ren3,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_swap23,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  input  [1:0]  io_req_bits_uop_fp_ctrl_typeTagIn,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_typeTagOut,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  input         io_req_bits_uop_fp_ctrl_toint,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_fastpipe,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_fma,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_uop_fp_ctrl_wflags,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  input  [4:0]  io_req_bits_uop_fcn_op,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  input  [2:0]  io_req_bits_uop_fp_rm,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  input  [1:0]  io_req_bits_uop_fp_typ,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  input  [64:0] io_req_bits_rs1_data,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_rs2_data,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
                io_req_bits_rs3_data,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  output [64:0] io_resp_bits_data,	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
  output [4:0]  io_resp_bits_fflags_bits	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:36:14
);

  wire [64:0] _fpmu_io_out_bits_data;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:84:20
  wire [4:0]  _fpmu_io_out_bits_exc;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:84:20
  wire        _fpiu_io_out_bits_lt;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20
  wire [63:0] _fpiu_io_out_bits_toint;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20
  wire [4:0]  _fpiu_io_out_bits_exc;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20
  wire        _sfma_io_out_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:71:20
  wire [64:0] _sfma_io_out_bits_data;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:71:20
  wire [4:0]  _sfma_io_out_bits_exc;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:71:20
  wire        _dfma_io_out_valid;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:67:20
  wire [64:0] _dfma_io_out_bits_data;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:67:20
  wire [4:0]  _dfma_io_out_bits_exc;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:67:20
  wire        _sfma_io_in_valid_T = io_req_valid & io_req_bits_uop_fp_ctrl_fma;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:68:36
  wire        _fpmu_double_T_1 = io_req_bits_uop_fp_ctrl_typeTagOut == 2'h1;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:68:74
  wire        _fpiu_io_in_bits_T = io_req_bits_uop_fp_ctrl_typeTagOut == 2'h0;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:59:47, :107:29
  wire [32:0] _sfma_io_in_bits_req_in2_T_1 =
    {io_req_bits_rs2_data[31], io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:0]}
    | ((&(io_req_bits_rs2_data[64:60])) ? 33'h0 : 33'hE0400000);	// generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}
  wire        _fpiu_io_in_valid_T_2 =
    io_req_valid
    & (io_req_bits_uop_fp_ctrl_toint | io_req_bits_uop_fp_ctrl_fastpipe
       & io_req_bits_uop_fp_ctrl_wflags);	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:76:{36,54,75}
  wire [2:0]  fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode =
    {io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:29]};	// generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14
  wire [11:0] _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2 =
    {3'h0, io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:23]} + 12'h700;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :281:19, :358:14
  wire [64:0] fpiu_io_in_bits_req_in1 =
    io_req_bits_uop_fp_ctrl_typeTagIn[0] | (&(io_req_bits_rs1_data[64:60]))
      ? (io_req_bits_uop_fp_ctrl_typeTagIn[0]
           ? io_req_bits_rs1_data
           : {io_req_bits_rs1_data[31],
              fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode == 3'h0
              | fpiu_io_in_bits_req_in1_prev_prev_expOut_expCode > 3'h5
                ? {io_req_bits_rs1_data[52],
                   io_req_bits_rs1_data[30:29],
                   _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2[8:0]}
                : _fpiu_io_in_bits_req_in1_prev_prev_expOut_commonCase_T_2,
              io_req_bits_rs1_data[22:0],
              29'h0})
      : 65'hE008000000000000;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:275:20, :276:18, :277:38, :279:26, :280:50, :281:{10,19,27,38,49,69}, :283:8, :332:{49,84}, :357:14, :358:14, :369:10, :372:31, generators/rocket-chip/src/main/scala/util/package.scala:38:47, :39:76
  wire [2:0]  fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode =
    {io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:29]};	// generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :279:26, :358:14
  wire [11:0] _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2 =
    {3'h0, io_req_bits_rs2_data[52], io_req_bits_rs2_data[30:23]} + 12'h700;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:276:18, :280:{31,50}, :281:19, :358:14
  wire [64:0] fpiu_io_in_bits_req_in2 =
    io_req_bits_uop_fp_ctrl_typeTagIn[0] | (&(io_req_bits_rs2_data[64:60]))
      ? (io_req_bits_uop_fp_ctrl_typeTagIn[0]
           ? io_req_bits_rs2_data
           : {io_req_bits_rs2_data[31],
              fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode == 3'h0
              | fpiu_io_in_bits_req_in2_prev_prev_expOut_expCode > 3'h5
                ? {io_req_bits_rs2_data[52],
                   io_req_bits_rs2_data[30:29],
                   _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2[8:0]}
                : _fpiu_io_in_bits_req_in2_prev_prev_expOut_commonCase_T_2,
              io_req_bits_rs2_data[22:0],
              29'h0})
      : 65'hE008000000000000;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:275:20, :276:18, :277:38, :279:26, :280:50, :281:{10,19,27,38,49,69}, :283:8, :332:{49,84}, :357:14, :358:14, :369:10, :372:31, generators/rocket-chip/src/main/scala/util/package.scala:38:47, :39:76
  reg         fpiu_out_REG;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:78:30
  reg         fpiu_out_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg  [63:0] fpiu_out_pipe_b_toint;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [4:0]  fpiu_out_pipe_b_exc;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg         fpiu_out_pipe_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg  [63:0] fpiu_out_pipe_pipe_b_toint;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [4:0]  fpiu_out_pipe_pipe_b_exc;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg         fpiu_out_pipe_pipe_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg  [63:0] fpiu_out_pipe_pipe_pipe_b_toint;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg  [4:0]  fpiu_out_pipe_pipe_pipe_b_exc;	// src/main/scala/chisel3/util/Valid.scala:142:26
  wire        _fpmu_double_T = io_req_valid & io_req_bits_uop_fp_ctrl_fastpipe;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:85:36
  reg         fpmu_double_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg         fpmu_double_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg         fpmu_double_pipe_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg         fpmu_double_pipe_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg         fpmu_double_pipe_pipe_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
  reg         fpmu_double_pipe_pipe_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
  reg         fpmu_double_pipe_pipe_pipe_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
    fpiu_out_REG <= _fpiu_io_in_valid_T_2 & ~io_req_bits_uop_fp_ctrl_fastpipe;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:76:36, :78:{30,48,51}
    if (fpiu_out_REG) begin	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:78:30
      fpiu_out_pipe_b_toint <= _fpiu_io_out_bits_toint;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20, src/main/scala/chisel3/util/Valid.scala:142:26
      fpiu_out_pipe_b_exc <= _fpiu_io_out_bits_exc;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20, src/main/scala/chisel3/util/Valid.scala:142:26
    end
    if (fpiu_out_pipe_v) begin	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpiu_out_pipe_pipe_b_toint <= fpiu_out_pipe_b_toint;	// src/main/scala/chisel3/util/Valid.scala:142:26
      fpiu_out_pipe_pipe_b_exc <= fpiu_out_pipe_b_exc;	// src/main/scala/chisel3/util/Valid.scala:142:26
    end
    if (fpiu_out_pipe_pipe_v) begin	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpiu_out_pipe_pipe_pipe_b_toint <= fpiu_out_pipe_pipe_b_toint;	// src/main/scala/chisel3/util/Valid.scala:142:26
      fpiu_out_pipe_pipe_pipe_b_exc <= fpiu_out_pipe_pipe_b_exc;	// src/main/scala/chisel3/util/Valid.scala:142:26
    end
    if (_fpmu_double_T)	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:85:36
      fpmu_double_pipe_b <= _fpmu_double_T_1;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:68:74, src/main/scala/chisel3/util/Valid.scala:142:26
    if (fpmu_double_pipe_v)	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_b <= fpmu_double_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
    if (fpmu_double_pipe_pipe_v)	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_pipe_b <= fpmu_double_pipe_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
    if (fpmu_double_pipe_pipe_pipe_v)	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_pipe_pipe_b <= fpmu_double_pipe_pipe_pipe_b;	// src/main/scala/chisel3/util/Valid.scala:142:26
    if (reset) begin	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      fpiu_out_pipe_v <= 1'h0;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, src/main/scala/chisel3/util/Valid.scala:141:24
      fpiu_out_pipe_pipe_v <= 1'h0;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, src/main/scala/chisel3/util/Valid.scala:141:24
      fpiu_out_pipe_pipe_pipe_v <= 1'h0;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_v <= 1'h0;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_v <= 1'h0;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_pipe_v <= 1'h0;	// generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, src/main/scala/chisel3/util/Valid.scala:141:24
    end
    else begin	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      fpiu_out_pipe_v <= fpiu_out_REG;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:78:30, src/main/scala/chisel3/util/Valid.scala:141:24
      fpiu_out_pipe_pipe_v <= fpiu_out_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpiu_out_pipe_pipe_pipe_v <= fpiu_out_pipe_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_v <= _fpmu_double_T;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:85:36, src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_v <= fpmu_double_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
      fpmu_double_pipe_pipe_pipe_v <= fpmu_double_pipe_pipe_v;	// src/main/scala/chisel3/util/Valid.scala:141:24
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      automatic logic [31:0] _RANDOM[0:33];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
        for (logic [5:0] i = 6'h0; i < 6'h22; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
        end	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
        fpiu_out_REG = _RANDOM[6'h0][0];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, :78:30
        fpiu_out_pipe_v = _RANDOM[6'h0][1];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, :78:30, src/main/scala/chisel3/util/Valid.scala:141:24
        fpiu_out_pipe_b_toint = {_RANDOM[6'h9][31:2], _RANDOM[6'hA], _RANDOM[6'hB][1:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpiu_out_pipe_b_exc = _RANDOM[6'hB][6:2];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpiu_out_pipe_pipe_v = _RANDOM[6'hB][7];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        fpiu_out_pipe_pipe_b_toint =
          {_RANDOM[6'h14][31:8], _RANDOM[6'h15], _RANDOM[6'h16][7:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpiu_out_pipe_pipe_b_exc = _RANDOM[6'h16][12:8];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpiu_out_pipe_pipe_pipe_v = _RANDOM[6'h16][13];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        fpiu_out_pipe_pipe_pipe_b_toint =
          {_RANDOM[6'h1F][31:14], _RANDOM[6'h20], _RANDOM[6'h21][13:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpiu_out_pipe_pipe_pipe_b_exc = _RANDOM[6'h21][18:14];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpmu_double_pipe_v = _RANDOM[6'h21][19];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        fpmu_double_pipe_b = _RANDOM[6'h21][20];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpmu_double_pipe_pipe_v = _RANDOM[6'h21][21];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        fpmu_double_pipe_pipe_b = _RANDOM[6'h21][22];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpmu_double_pipe_pipe_pipe_v = _RANDOM[6'h21][23];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
        fpmu_double_pipe_pipe_pipe_b = _RANDOM[6'h21][24];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
        fpmu_double_pipe_pipe_pipe_pipe_b = _RANDOM[6'h21][26];	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, src/main/scala/chisel3/util/Valid.scala:142:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FPUFMAPipe_l4_f64 dfma (	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:67:20
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_sfma_io_in_valid_T & _fpmu_double_T_1),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:68:{36,51,74}
    .io_in_bits_ren3   (io_req_bits_uop_fp_ctrl_ren3),
    .io_in_bits_swap23 (io_req_bits_uop_fp_ctrl_swap23),
    .io_in_bits_rm     (io_req_bits_uop_fp_rm),
    .io_in_bits_fmaCmd (io_req_bits_uop_fcn_op[1:0]),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:63:16
    .io_in_bits_in1    (io_req_bits_rs1_data),
    .io_in_bits_in2    (io_req_bits_rs2_data),
    .io_in_bits_in3
      (io_req_bits_uop_fp_ctrl_swap23 ? io_req_bits_rs2_data : io_req_bits_rs3_data),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:55:13, :56:{27,37}
    .io_out_valid      (_dfma_io_out_valid),
    .io_out_bits_data  (_dfma_io_out_bits_data),
    .io_out_bits_exc   (_dfma_io_out_bits_exc)
  );
  FPUFMAPipe_l4_f32 sfma (	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:71:20
    .clock             (clock),
    .reset             (reset),
    .io_in_valid       (_sfma_io_in_valid_T & _fpiu_io_in_bits_T),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:59:47, :68:36, :72:51
    .io_in_bits_ren3   (io_req_bits_uop_fp_ctrl_ren3),
    .io_in_bits_swap23 (io_req_bits_uop_fp_ctrl_swap23),
    .io_in_bits_rm     (io_req_bits_uop_fp_rm),
    .io_in_bits_fmaCmd (io_req_bits_uop_fcn_op[1:0]),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:63:16
    .io_in_bits_in1
      ({32'h0,
        {io_req_bits_rs1_data[31], io_req_bits_rs1_data[52], io_req_bits_rs1_data[30:0]}
          | ((&(io_req_bits_rs1_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:53:13, generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}
    .io_in_bits_in2    ({32'h0, _sfma_io_in_bits_req_in2_T_1}),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:53:13, :54:13, generators/rocket-chip/src/main/scala/tile/FPU.scala:372:26
    .io_in_bits_in3
      ({32'h0,
        io_req_bits_uop_fp_ctrl_swap23
          ? _sfma_io_in_bits_req_in2_T_1
          : {io_req_bits_rs3_data[31],
             io_req_bits_rs3_data[52],
             io_req_bits_rs3_data[30:0]}
            | ((&(io_req_bits_rs3_data[64:60])) ? 33'h0 : 33'hE0400000)}),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:53:13, :55:13, :56:{27,37}, generators/rocket-chip/src/main/scala/tile/FPU.scala:332:{49,84}, :356:31, :357:14, :358:14, :359:14, :372:{26,31}
    .io_out_valid      (_sfma_io_out_valid),
    .io_out_bits_data  (_sfma_io_out_bits_data),
    .io_out_bits_exc   (_sfma_io_out_bits_exc)
  );
  FPToInt fpiu (	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20
    .clock                 (clock),
    .io_in_valid           (_fpiu_io_in_valid_T_2),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:76:36
    .io_in_bits_ren2       (io_req_bits_uop_fp_ctrl_ren2),
    .io_in_bits_typeTagOut (io_req_bits_uop_fp_ctrl_typeTagOut),
    .io_in_bits_wflags     (io_req_bits_uop_fp_ctrl_wflags),
    .io_in_bits_rm         (io_req_bits_uop_fp_rm),
    .io_in_bits_typ        (io_req_bits_uop_fp_typ),
    .io_in_bits_fmt
      (io_req_bits_uop_fp_ctrl_toint & _fpiu_io_in_bits_T
       & ~io_req_bits_uop_fp_ctrl_wflags
         ? 2'h0
         : {1'h0, |io_req_bits_uop_fp_ctrl_typeTagIn}),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:58:{13,24}, :59:{47,53,56,73}, :60:15, :107:29, generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19
    .io_in_bits_in1        (fpiu_io_in_bits_req_in1),	// generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10
    .io_in_bits_in2        (fpiu_io_in_bits_req_in2),	// generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10
    .io_out_bits_in_rm     (/* unused */),
    .io_out_bits_in_in1    (/* unused */),
    .io_out_bits_in_in2    (/* unused */),
    .io_out_bits_lt        (_fpiu_io_out_bits_lt),
    .io_out_bits_toint     (_fpiu_io_out_bits_toint),
    .io_out_bits_exc       (_fpiu_io_out_bits_exc)
  );
  FPToFP fpmu (	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:84:20
    .clock                 (clock),
    .reset                 (reset),
    .io_in_valid           (_fpmu_double_T),	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:85:36
    .io_in_bits_ren2       (io_req_bits_uop_fp_ctrl_ren2),
    .io_in_bits_typeTagOut (io_req_bits_uop_fp_ctrl_typeTagOut),
    .io_in_bits_wflags     (io_req_bits_uop_fp_ctrl_wflags),
    .io_in_bits_rm         (io_req_bits_uop_fp_rm),
    .io_in_bits_in1        (fpiu_io_in_bits_req_in1),	// generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10
    .io_in_bits_in2        (fpiu_io_in_bits_req_in2),	// generators/rocket-chip/src/main/scala/tile/FPU.scala:369:10
    .io_out_bits_data      (_fpmu_io_out_bits_data),
    .io_out_bits_exc       (_fpmu_io_out_bits_exc),
    .io_lt                 (_fpiu_io_out_bits_lt)	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:75:20
  );
  assign io_resp_bits_data =
    _dfma_io_out_valid
      ? _dfma_io_out_bits_data
      : _sfma_io_out_valid
          ? {12'hFFF,
             _sfma_io_out_bits_data[31],
             20'hFFFFF,
             _sfma_io_out_bits_data[32],
             _sfma_io_out_bits_data[30:0]}
          : fpiu_out_pipe_pipe_pipe_v
              ? {1'h0, fpiu_out_pipe_pipe_pipe_b_toint}
              : fpmu_double_pipe_pipe_pipe_pipe_b
                  ? _fpmu_io_out_bits_data
                  : {12'hFFF,
                     _fpmu_io_out_bits_data[31],
                     20'hFFFFF,
                     _fpmu_io_out_bits_data[32],
                     _fpmu_io_out_bits_data[30:0]};	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, :67:20, :71:20, :81:20, :84:20, :96:8, :97:8, :98:8, generators/rocket-chip/src/main/scala/tile/FPU.scala:281:19, :336:26, :338:42, :340:8, :342:8, :343:8, generators/rocket-chip/src/main/scala/util/package.scala:39:76, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
  assign io_resp_bits_fflags_bits =
    _dfma_io_out_valid
      ? _dfma_io_out_bits_exc
      : _sfma_io_out_valid
          ? _sfma_io_out_bits_exc
          : fpiu_out_pipe_pipe_pipe_v
              ? fpiu_out_pipe_pipe_pipe_b_exc
              : _fpmu_io_out_bits_exc;	// generators/boom/src/main/scala/v4/exu/execution-units/fpu.scala:34:7, :67:20, :71:20, :84:20, :102:8, :103:8, :104:8, src/main/scala/chisel3/util/Valid.scala:141:24, :142:26
endmodule

