// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ImmRenameStage(	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
  input        clock,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
               reset,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
  output       io_ren_stalls_0,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_kill,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_fire_0,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_uops_0_iq_type_0,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_uops_0_iq_type_1,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_uops_0_iq_type_2,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [2:0] io_dec_uops_0_br_tag,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [3:0] io_dec_uops_0_br_type,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_dec_uops_0_is_sfb,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_uops_0_imm_rename,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [2:0] io_dec_uops_0_imm_sel,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [4:0] io_dec_uops_0_pimm,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [5:0] io_dec_uops_0_lrs1,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_uops_0_lrs2,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [1:0] io_dec_uops_0_lrs1_rtype,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dec_uops_0_lrs2_rtype,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  output [2:0] io_ren2_uops_0_imm_sel,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  output [4:0] io_ren2_uops_0_pimm,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [2:0] io_brupdate_b2_uop_br_tag,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_brupdate_b2_mispredict,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dis_fire_0,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_dis_ready,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
               io_wakeups_0_valid,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [4:0] io_wakeups_0_bits_uop_pimm,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_wakeups_1_valid,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [4:0] io_wakeups_1_bits_uop_pimm,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_wakeups_2_valid,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [4:0] io_wakeups_2_bits_uop_pimm,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_wakeups_3_valid,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input  [4:0] io_wakeups_3_bits_uop_pimm,	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
  input        io_rollback	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:33:14
);

  reg         r_uop_imm_rename;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  wire        _freelist_io_alloc_pregs_0_valid;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:417:24
  wire [4:0]  _freelist_io_alloc_pregs_0_bits;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:417:24
  wire [31:0] _freelist_io_debug_freelist;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:417:24
  wire        ren2_alloc_fire_0 = io_dis_fire_0 & r_uop_imm_rename;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:79:79, :94:23
  reg         r_valid;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:93:27
  reg         r_uop_iq_type_0;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg         r_uop_iq_type_1;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg         r_uop_iq_type_2;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [2:0]  r_uop_br_tag;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [3:0]  r_uop_br_type;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg         r_uop_is_sfb;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [2:0]  r_uop_imm_sel;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [4:0]  r_uop_pimm;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [5:0]  r_uop_lrs1;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [5:0]  r_uop_lrs2;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [1:0]  r_uop_lrs1_rtype;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg  [1:0]  r_uop_lrs2_rtype;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
  reg         REG;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:458:19
  `ifndef SYNTHESIS	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:109:11
    always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:109:11
      if (~reset & r_valid & r_uop_lrs1_rtype == 2'h0 & r_uop_lrs1 == 6'h0) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:93:27, :94:23, :109:{11,42,67}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:109:11
          $error("Assertion failed\n    at rename-stage.scala:109 assert(!(r_valid && r_uop.lrs1_rtype === RT_FIX && r_uop.lrs1 === 0.U))\n");	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:109:11
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:109:11
          $fatal;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:109:11
      end
      if (~reset & r_valid & r_uop_lrs2_rtype == 2'h0 & r_uop_lrs2 == 6'h0) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:93:27, :94:23, :109:{11,42,67}, :110:{11,42,67}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:110:11
          $error("Assertion failed\n    at rename-stage.scala:110 assert(!(r_valid && r_uop.lrs2_rtype === RT_FIX && r_uop.lrs2 === 0.U))\n");	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:110:11
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:110:11
          $fatal;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:110:11
      end
      if (~reset
          & ~(~ren2_alloc_fire_0 | r_uop_iq_type_2 | r_uop_iq_type_0
              | r_uop_iq_type_1)) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:79:79, :94:23, :109:11, :432:{11,12,96}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:432:11
          $error("Assertion failed\n    at rename-stage.scala:432 assert(!ren2_alloc_fire(w) || ren2_uops(w).iq_type(IQ_ALU) || ren2_uops(w).iq_type(IQ_MEM) || ren2_uops(w).iq_type(IQ_UNQ))\n");	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:432:11
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:432:11
          $fatal;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:432:11
      end
      if (~reset
          & ~(~REG
              | {1'h0,
                 {1'h0,
                  {1'h0,
                   {1'h0,
                    {1'h0, _freelist_io_debug_freelist[0]}
                      + {1'h0, _freelist_io_debug_freelist[1]}}
                     + {1'h0,
                        {1'h0, _freelist_io_debug_freelist[2]}
                          + {1'h0, _freelist_io_debug_freelist[3]}}}
                    + {1'h0,
                       {1'h0,
                        {1'h0, _freelist_io_debug_freelist[4]}
                          + {1'h0, _freelist_io_debug_freelist[5]}}
                         + {1'h0,
                            {1'h0, _freelist_io_debug_freelist[6]}
                              + {1'h0, _freelist_io_debug_freelist[7]}}}}
                   + {1'h0,
                      {1'h0,
                       {1'h0,
                        {1'h0, _freelist_io_debug_freelist[8]}
                          + {1'h0, _freelist_io_debug_freelist[9]}}
                         + {1'h0,
                            {1'h0, _freelist_io_debug_freelist[10]}
                              + {1'h0, _freelist_io_debug_freelist[11]}}}
                        + {1'h0,
                           {1'h0,
                            {1'h0, _freelist_io_debug_freelist[12]}
                              + {1'h0, _freelist_io_debug_freelist[13]}}
                             + {1'h0,
                                {1'h0, _freelist_io_debug_freelist[14]}
                                  + {1'h0, _freelist_io_debug_freelist[15]}}}}}
              + {1'h0,
                 {1'h0,
                  {1'h0,
                   {1'h0,
                    {1'h0, _freelist_io_debug_freelist[16]}
                      + {1'h0, _freelist_io_debug_freelist[17]}}
                     + {1'h0,
                        {1'h0, _freelist_io_debug_freelist[18]}
                          + {1'h0, _freelist_io_debug_freelist[19]}}}
                    + {1'h0,
                       {1'h0,
                        {1'h0, _freelist_io_debug_freelist[20]}
                          + {1'h0, _freelist_io_debug_freelist[21]}}
                         + {1'h0,
                            {1'h0, _freelist_io_debug_freelist[22]}
                              + {1'h0, _freelist_io_debug_freelist[23]}}}}
                   + {1'h0,
                      {1'h0,
                       {1'h0,
                        {1'h0, _freelist_io_debug_freelist[24]}
                          + {1'h0, _freelist_io_debug_freelist[25]}}
                         + {1'h0,
                            {1'h0, _freelist_io_debug_freelist[26]}
                              + {1'h0, _freelist_io_debug_freelist[27]}}}
                        + {1'h0,
                           {1'h0,
                            {1'h0, _freelist_io_debug_freelist[28]}
                              + {1'h0, _freelist_io_debug_freelist[29]}}
                             + {1'h0,
                                {1'h0, _freelist_io_debug_freelist[30]}
                                  + {1'h0,
                                     _freelist_io_debug_freelist[31]}}}}} == 6'h20)) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:90:25, :109:11, :417:24, :458:{10,11,19,33,44,73}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:458:10
          $error("Assertion failed: [freelist] Leaking physical registers.\n    at rename-stage.scala:458 assert (!RegNext(io.rollback) || PopCount(freelist.io.debug_freelist) === (numImmPhysRegs).U,\n");	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:458:10
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:458:10
          $fatal;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:458:10
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
    if (reset)	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      r_valid <= 1'h0;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:90:25, :93:27
    else	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      r_valid <= ~io_kill & (io_dis_ready ? io_dec_fire_0 : r_valid & ~io_dis_fire_0);	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:93:27, :99:20, :100:15, :101:30, :102:15, :105:{15,26,29}
    if (io_kill | ~io_dis_ready) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:97:14, :99:20, :101:30
    end
    else begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:97:14, :99:20, :101:30
      r_uop_iq_type_0 <= io_dec_uops_0_iq_type_0;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_iq_type_1 <= io_dec_uops_0_iq_type_1;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_iq_type_2 <= io_dec_uops_0_iq_type_2;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_br_tag <= io_dec_uops_0_br_tag;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_br_type <= io_dec_uops_0_br_type;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_is_sfb <= io_dec_uops_0_is_sfb;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_imm_rename <= io_dec_uops_0_imm_rename;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_imm_sel <= io_dec_uops_0_imm_sel;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_pimm <= io_dec_uops_0_pimm;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_lrs1 <= io_dec_uops_0_lrs1;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_lrs2 <= io_dec_uops_0_lrs2;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_lrs1_rtype <= io_dec_uops_0_lrs1_rtype;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
      r_uop_lrs2_rtype <= io_dec_uops_0_lrs2_rtype;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
    end
    REG <= io_rollback;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:458:19
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      automatic logic [31:0] _RANDOM[0:12];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
        for (logic [3:0] i = 4'h0; i < 4'hD; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
        end	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
        r_valid = _RANDOM[4'h0][0];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:93:27, :414:7
        r_uop_iq_type_0 = _RANDOM[4'h3][10];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_iq_type_1 = _RANDOM[4'h3][11];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_iq_type_2 = _RANDOM[4'h3][12];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_br_tag = _RANDOM[4'h4][11:9];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_br_type = _RANDOM[4'h4][15:12];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_is_sfb = _RANDOM[4'h4][16];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_imm_rename = _RANDOM[4'h5][5];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_imm_sel = _RANDOM[4'h5][8:6];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_pimm = _RANDOM[4'h5][13:9];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_lrs1 = _RANDOM[4'hB][11:6];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_lrs2 = _RANDOM[4'hB][17:12];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_lrs1_rtype = _RANDOM[4'hB][27:26];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        r_uop_lrs2_rtype = _RANDOM[4'hB][29:28];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
        REG = _RANDOM[4'hC][22];	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7, :458:19
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:414:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  RenameFreeList_2 freelist (	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:417:24
    .clock                     (clock),
    .reset                     (reset),
    .io_reqs_0                 (ren2_alloc_fire_0),	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:79:79
    .io_alloc_pregs_0_valid    (_freelist_io_alloc_pregs_0_valid),
    .io_alloc_pregs_0_bits     (_freelist_io_alloc_pregs_0_bits),
    .io_dealloc_0_valid        (io_wakeups_0_valid),
    .io_dealloc_0_bits         (io_wakeups_0_bits_uop_pimm),
    .io_dealloc_1_valid        (io_wakeups_1_valid),
    .io_dealloc_1_bits         (io_wakeups_1_bits_uop_pimm),
    .io_dealloc_2_valid        (io_wakeups_2_valid),
    .io_dealloc_2_bits         (io_wakeups_2_bits_uop_pimm),
    .io_dealloc_3_valid        (io_wakeups_3_valid),
    .io_dealloc_3_bits         (io_wakeups_3_bits_uop_pimm),
    .io_ren_br_tags_1_valid
      (io_dis_fire_0
       & ((r_uop_br_type == 4'h1 | r_uop_br_type == 4'h2 | r_uop_br_type == 4'h3
           | r_uop_br_type == 4'h4 | r_uop_br_type == 4'h5 | r_uop_br_type == 4'h6)
          & ~r_uop_is_sfb | r_uop_br_type == 4'h8)),	// generators/boom/src/main/scala/v4/common/micro-op.scala:119:34, :160:{33,36,45}, generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :117:45, :414:7, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59
    .io_ren_br_tags_1_bits     (r_uop_br_tag),	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23
    .io_brupdate_b2_uop_br_tag (io_brupdate_b2_uop_br_tag),
    .io_brupdate_b2_mispredict (io_brupdate_b2_mispredict),
    .io_rollback               (io_rollback),
    .io_debug_freelist         (_freelist_io_debug_freelist)
  );
  assign io_ren_stalls_0 = r_uop_imm_rename & ~_freelist_io_alloc_pregs_0_valid;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7, :417:24, :437:{49,52}
  assign io_ren2_uops_0_imm_sel = r_uop_imm_sel;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7
  assign io_ren2_uops_0_pimm =
    r_uop_imm_rename ? _freelist_io_alloc_pregs_0_bits : r_uop_pimm;	// generators/boom/src/main/scala/v4/exu/rename/rename-stage.scala:94:23, :414:7, :417:24, :439:21, :440:36, :441:28
endmodule

