// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module PartiallyPortedRF(	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
  input         clock,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
                reset,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
                io_arb_read_reqs_0_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_arb_read_reqs_0_bits,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_arb_read_reqs_1_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_arb_read_reqs_1_bits,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  output        io_arb_read_reqs_2_ready,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_arb_read_reqs_2_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_arb_read_reqs_2_bits,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  output [64:0] io_rrd_read_resps_0,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
                io_rrd_read_resps_1,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
                io_rrd_read_resps_2,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_write_ports_0_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_write_ports_0_bits_addr,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [64:0] io_write_ports_0_bits_data,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input         io_write_ports_1_valid,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [5:0]  io_write_ports_1_bits_addr,	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
  input  [64:0] io_write_ports_1_bits_data	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:31:14
);

  wire [64:0] _rf_io_rrd_read_resps_0;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18
  wire [64:0] _rf_io_rrd_read_resps_1;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18
  wire [64:0] _rf_io_rrd_read_resps_2;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18
  wire        use_port_3 = ~io_arb_read_reqs_0_valid & io_arb_read_reqs_1_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :164:66
  wire        _GEN = use_port_3 | io_arb_read_reqs_0_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33
  wire        use_port_4 = ~use_port_3 & io_arb_read_reqs_1_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :164:66
  wire        _GEN_0 = use_port_4 | use_port_3;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :165:32
  wire        use_port_5 = ~_GEN_0 & io_arb_read_reqs_1_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,45}, :165:32
  wire        use_port_6 = ~_GEN & io_arb_read_reqs_2_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :163:33
  wire        use_port_7 = ~use_port_6 & ~use_port_4 & io_arb_read_reqs_2_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{29,45}, :164:66
  wire        _GEN_1 = use_port_7 | use_port_6;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :165:32
  wire        use_port_8 = ~_GEN_1 & ~use_port_5 & io_arb_read_reqs_2_valid;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{13,29,45}, :165:32
  wire        io_arb_read_reqs_2_ready_0 =
    {1'h0, io_arb_read_reqs_0_valid} + {1'h0, io_arb_read_reqs_1_valid} != 2'h3;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:{42,82}
  `ifndef SYNTHESIS	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
    always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
      if (~reset
          & ~(~io_write_ports_0_valid | ~io_write_ports_1_valid
              | io_write_ports_0_bits_addr != io_write_ports_1_bits_addr)) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:{15,16}, :46:{16,41}, :47:45
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
          $error("Assertion failed: [regfile] too many writers a register\n    at regfile.scala:45 assert(!io.write_ports(i).valid ||\n");	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
          $fatal;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15
      end
      if (~reset & io_arb_read_reqs_1_valid & ~(use_port_5 | _GEN_0)) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:45, :165:32, :168:{11,42}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
          $fatal;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
      end
      if (~reset & io_arb_read_reqs_2_ready_0 & io_arb_read_reqs_2_valid
          & ~(use_port_8 | _GEN_1)) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:45:15, :157:45, :165:32, :167:82, :168:{11,42}
        if (`ASSERT_VERBOSE_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
          $error("Assertion failed\n    at regfile.scala:168 assert(!(io.arb_read_reqs(i).fire && !read_issued))\n");	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
        if (`STOP_COND_)	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
          $fatal;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:168:11
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg  [2:0]  rrd_data_sels_0;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30
  reg  [2:0]  rrd_data_sels_1;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30
  reg  [2:0]  rrd_data_sels_2;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:177:30
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
    rrd_data_sels_0 <= 3'h1;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:160:22, :177:30
    rrd_data_sels_1 <= use_port_5 ? 3'h4 : use_port_4 ? 3'h2 : 3'h1;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{45,75}, :160:22, :177:30
    rrd_data_sels_2 <= use_port_8 ? 3'h4 : use_port_7 ? 3'h2 : 3'h1;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:{45,75}, :160:22, :177:30
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
      automatic logic [31:0] _RANDOM[0:0];	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
        rrd_data_sels_0 = _RANDOM[/*Zero width*/ 1'b0][2:0];	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30
        rrd_data_sels_1 = _RANDOM[/*Zero width*/ 1'b0][5:3];	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30
        rrd_data_sels_2 = _RANDOM[/*Zero width*/ 1'b0][8:6];	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :177:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FullyPortedRF rf (	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:138:18
    .clock                      (clock),
    .reset                      (reset),
    .io_arb_read_reqs_0_bits
      ((io_arb_read_reqs_0_valid ? io_arb_read_reqs_0_bits : 6'h0)
       | (io_arb_read_reqs_0_valid | ~use_port_3 ? 6'h0 : io_arb_read_reqs_1_bits)
       | (_GEN | ~use_port_6 ? 6'h0 : io_arb_read_reqs_2_bits)),	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :163:33, :164:{37,42,63,66}
    .io_arb_read_reqs_1_bits
      ((use_port_4 ? io_arb_read_reqs_1_bits : 6'h0)
       | (use_port_4 | ~use_port_7 ? 6'h0 : io_arb_read_reqs_2_bits)),	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :164:{37,42,63,66}
    .io_arb_read_reqs_2_bits
      ((use_port_5 ? io_arb_read_reqs_1_bits : 6'h0)
       | (use_port_5 | ~use_port_8 ? 6'h0 : io_arb_read_reqs_2_bits)),	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:157:45, :164:{37,42,63,66}
    .io_rrd_read_resps_0        (_rf_io_rrd_read_resps_0),
    .io_rrd_read_resps_1        (_rf_io_rrd_read_resps_1),
    .io_rrd_read_resps_2        (_rf_io_rrd_read_resps_2),
    .io_write_ports_0_valid     (io_write_ports_0_valid),
    .io_write_ports_0_bits_addr (io_write_ports_0_bits_addr),
    .io_write_ports_0_bits_data (io_write_ports_0_bits_data),
    .io_write_ports_1_valid     (io_write_ports_1_valid),
    .io_write_ports_1_bits_addr (io_write_ports_1_bits_addr),
    .io_write_ports_1_bits_data (io_write_ports_1_bits_data)
  );
  assign io_arb_read_reqs_2_ready = io_arb_read_reqs_2_ready_0;	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :167:82
  assign io_rrd_read_resps_0 =
    (rrd_data_sels_0[0] ? _rf_io_rrd_read_resps_0 : 65'h0)
    | (rrd_data_sels_0[1] ? _rf_io_rrd_read_resps_1 : 65'h0)
    | (rrd_data_sels_0[2] ? _rf_io_rrd_read_resps_2 : 65'h0);	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73
  assign io_rrd_read_resps_1 =
    (rrd_data_sels_1[0] ? _rf_io_rrd_read_resps_0 : 65'h0)
    | (rrd_data_sels_1[1] ? _rf_io_rrd_read_resps_1 : 65'h0)
    | (rrd_data_sels_1[2] ? _rf_io_rrd_read_resps_2 : 65'h0);	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73
  assign io_rrd_read_resps_2 =
    (rrd_data_sels_2[0] ? _rf_io_rrd_read_resps_0 : 65'h0)
    | (rrd_data_sels_2[1] ? _rf_io_rrd_read_resps_1 : 65'h0)
    | (rrd_data_sels_2[2] ? _rf_io_rrd_read_resps_2 : 65'h0);	// generators/boom/src/main/scala/v4/exu/register-read/regfile.scala:128:7, :138:18, :177:30, :180:52, src/main/scala/chisel3/util/Mux.scala:30:73
endmodule

