// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module RenameBusyTable_1(	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
  input        clock,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
               reset,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
  input  [5:0] io_ren_uops_0_pdst,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
               io_ren_uops_0_prs1,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
               io_ren_uops_0_prs2,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
               io_ren_uops_0_prs3,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
  output       io_busy_resps_0_prs1_busy,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
               io_busy_resps_0_prs2_busy,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
               io_busy_resps_0_prs3_busy,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
  input        io_rebusy_reqs_0,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
               io_wakeups_0_valid,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
  input  [5:0] io_wakeups_0_bits_uop_pdst,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
  input        io_wakeups_1_valid,	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
  input  [5:0] io_wakeups_1_bits_uop_pdst	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:36:14
);

  reg         wakeups_wu_valid_REG;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:48:24
  reg  [5:0]  wakeups_wu_bits_REG_uop_pdst;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:49:24
  reg         wakeups_wu_valid_REG_2;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:48:24
  reg  [5:0]  wakeups_wu_bits_REG_1_uop_pdst;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:49:24
  reg  [47:0] busy_table;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:53:27
  wire [47:0] _io_busy_resps_0_prs1_busy_T = busy_table >> io_ren_uops_0_prs1;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:53:27, :74:45
  wire [47:0] _io_busy_resps_0_prs2_busy_T = busy_table >> io_ren_uops_0_prs2;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:53:27, :75:45
  wire [47:0] _io_busy_resps_0_prs3_busy_T = busy_table >> io_ren_uops_0_prs3;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:53:27, :76:45
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
    wakeups_wu_valid_REG <= io_wakeups_0_valid;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:48:24
    wakeups_wu_bits_REG_uop_pdst <= io_wakeups_0_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:49:24
    wakeups_wu_valid_REG_2 <= io_wakeups_1_valid;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:48:24
    wakeups_wu_bits_REG_1_uop_pdst <= io_wakeups_1_bits_uop_pdst;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:49:24
    if (reset)	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      busy_table <= 48'h0;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:53:27
    else begin	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      automatic logic [63:0] _busy_table_next_T = 64'h1 << io_ren_uops_0_pdst;	// src/main/scala/chisel3/util/OneHot.scala:58:35
      automatic logic [63:0] _busy_table_next_T_8;	// src/main/scala/chisel3/util/OneHot.scala:58:35
      automatic logic [63:0] _busy_table_next_T_4;	// src/main/scala/chisel3/util/OneHot.scala:58:35
      _busy_table_next_T_8 = 64'h1 << wakeups_wu_bits_REG_1_uop_pdst;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:49:24, src/main/scala/chisel3/util/OneHot.scala:58:35
      _busy_table_next_T_4 = 64'h1 << wakeups_wu_bits_REG_uop_pdst;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:49:24, src/main/scala/chisel3/util/OneHot.scala:58:35
      busy_table <=
        ~(_busy_table_next_T_4[47:0] & {48{wakeups_wu_valid_REG}}
          | _busy_table_next_T_8[47:0] & {48{wakeups_wu_valid_REG_2}}) & busy_table
        | _busy_table_next_T[47:0] & {48{io_rebusy_reqs_0}};	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:48:24, :53:27, :55:{34,36}, :56:{31,37}, :57:14, :59:39, :61:{51,57}, src/main/scala/chisel3/util/OneHot.scala:58:35
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      automatic logic [31:0] _RANDOM[0:27];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
        for (logic [4:0] i = 5'h0; i < 5'h1C; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
        end	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
        wakeups_wu_valid_REG = _RANDOM[5'h0][0];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :48:24
        wakeups_wu_bits_REG_uop_pdst = _RANDOM[5'h7][15:10];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :49:24
        wakeups_wu_valid_REG_2 = _RANDOM[5'hC][26];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :48:24
        wakeups_wu_bits_REG_1_uop_pdst = _RANDOM[5'h14][9:4];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :49:24
        busy_table = {_RANDOM[5'h19][31:20], _RANDOM[5'h1A], _RANDOM[5'h1B][3:0]};	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :53:27
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_busy_resps_0_prs1_busy =
    ~(wakeups_wu_valid_REG & wakeups_wu_bits_REG_uop_pdst == io_ren_uops_0_prs1
      | wakeups_wu_valid_REG_2 & wakeups_wu_bits_REG_1_uop_pdst == io_ren_uops_0_prs1)
    & _io_busy_resps_0_prs1_busy_T[0];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :48:24, :49:24, :70:{49,68}, :74:{32,45}, :78:{30,36}, :79:34
  assign io_busy_resps_0_prs2_busy =
    ~(wakeups_wu_valid_REG & wakeups_wu_bits_REG_uop_pdst == io_ren_uops_0_prs2
      | wakeups_wu_valid_REG_2 & wakeups_wu_bits_REG_1_uop_pdst == io_ren_uops_0_prs2)
    & _io_busy_resps_0_prs2_busy_T[0];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :48:24, :49:24, :71:{49,68}, :75:{32,45}, :81:{30,36}, :82:34
  assign io_busy_resps_0_prs3_busy =
    ~(wakeups_wu_valid_REG & wakeups_wu_bits_REG_uop_pdst == io_ren_uops_0_prs3
      | wakeups_wu_valid_REG_2 & wakeups_wu_bits_REG_1_uop_pdst == io_ren_uops_0_prs3)
    & _io_busy_resps_0_prs3_busy_T[0];	// generators/boom/src/main/scala/v4/exu/rename/rename-busytable.scala:27:7, :48:24, :49:24, :72:{49,68}, :76:{32,45}, :84:{30,36}, :85:34
endmodule

