// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// VCS coverage exclude_file
module tag_array_64x88(	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
  input  [5:0]  RW0_addr,
  input         RW0_en,
                RW0_clk,
                RW0_wmode,
  input  [87:0] RW0_wdata,
  output [87:0] RW0_rdata,
  input  [3:0]  RW0_wmask
);

  reg [87:0] Memory[0:63];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
  reg [5:0]  _RW0_raddr_d0;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
  reg        _RW0_ren_d0;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
  reg        _RW0_rmode_d0;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
  always @(posedge RW0_clk) begin	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    _RW0_raddr_d0 <= RW0_addr;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    _RW0_ren_d0 <= RW0_en;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    _RW0_rmode_d0 <= RW0_wmode;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    if (RW0_en & RW0_wmask[0] & RW0_wmode)	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      Memory[RW0_addr][32'h0 +: 22] <= RW0_wdata[21:0];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    if (RW0_en & RW0_wmask[1] & RW0_wmode)	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      Memory[RW0_addr][32'h16 +: 22] <= RW0_wdata[43:22];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    if (RW0_en & RW0_wmask[2] & RW0_wmode)	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      Memory[RW0_addr][32'h2C +: 22] <= RW0_wdata[65:44];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    if (RW0_en & RW0_wmask[3] & RW0_wmode)	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      Memory[RW0_addr][32'h42 +: 22] <= RW0_wdata[87:66];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    `ifdef RANDOMIZE_REG_INIT	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      reg [31:0] _RANDOM;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    `endif // RANDOMIZE_REG_INIT
    reg [95:0] _RANDOM_MEM;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
    initial begin	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      `INIT_RANDOM_PROLOG_	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      `ifdef RANDOMIZE_MEM_INIT	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
        for (logic [6:0] i = 7'h0; i < 7'h40; i += 7'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h60; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
          end	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
          Memory[i[5:0]] = _RANDOM_MEM[87:0];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
        end	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      `endif // RANDOMIZE_MEM_INIT
      `ifdef RANDOMIZE_REG_INIT	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
        _RANDOM = {`RANDOM};	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
        _RW0_raddr_d0 = _RANDOM[5:0];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
        _RW0_ren_d0 = _RANDOM[6];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
        _RW0_rmode_d0 = _RANDOM[7];	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign RW0_rdata = _RW0_ren_d0 & ~_RW0_rmode_d0 ? Memory[_RW0_raddr_d0] : 88'bx;	// generators/rocket-chip/src/main/scala/rocket/HellaCache.scala:339:30
endmodule

