// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TageTable_5(	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
  input         clock,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
                reset,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
                io_f1_req_valid,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input  [39:0] io_f1_req_pc,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input  [63:0] io_f1_req_ghist,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output        io_f2_resp_0_valid,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [2:0]  io_f2_resp_0_bits_ctr,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [1:0]  io_f2_resp_0_bits_u,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output        io_f2_resp_1_valid,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [2:0]  io_f2_resp_1_bits_ctr,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [1:0]  io_f2_resp_1_bits_u,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output        io_f2_resp_2_valid,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [2:0]  io_f2_resp_2_bits_ctr,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [1:0]  io_f2_resp_2_bits_u,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output        io_f2_resp_3_valid,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [2:0]  io_f2_resp_3_bits_ctr,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  output [1:0]  io_f2_resp_3_bits_u,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input         io_update_mask_0,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_mask_1,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_mask_2,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_mask_3,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_taken_0,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_taken_1,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_taken_2,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_taken_3,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_alloc_0,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_alloc_1,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_alloc_2,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_alloc_3,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input  [2:0]  io_update_old_ctr_0,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_old_ctr_1,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_old_ctr_2,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_old_ctr_3,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input  [39:0] io_update_pc,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input  [63:0] io_update_hist,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input         io_update_u_mask_0,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_u_mask_1,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_u_mask_2,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_u_mask_3,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
  input  [1:0]  io_update_u_0,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_u_1,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_u_2,	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
                io_update_u_3	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
);

  wire [2:0]  update_wdata_3_ctr;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:168:33
  wire [2:0]  update_wdata_2_ctr;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:168:33
  wire [2:0]  update_wdata_1_ctr;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:168:33
  wire [2:0]  update_wdata_0_ctr;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:168:33
  wire        wdata_1_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_6;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_5;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_4;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_2;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire        wdata_1_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:145:20
  wire [12:0] wdata_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:130:20
  wire [12:0] wdata_2;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:130:20
  wire [12:0] wdata_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:130:20
  wire [12:0] wdata_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:130:20
  wire        s2_req_rtage_3_valid;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire [8:0]  s2_req_rtage_3_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire        s2_req_rtage_2_valid;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire [8:0]  s2_req_rtage_2_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire        s2_req_rtage_1_valid;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire [8:0]  s2_req_rtage_1_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire        s2_req_rtage_0_valid;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire [8:0]  s2_req_rtage_0_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:126:49
  wire [51:0] _tage_table_64_ext_R0_data;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27
  wire [7:0]  _tage_u_64_ext_R0_data;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:89:27
  reg         doing_reset;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28
  reg  [6:0]  reset_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:73:26
  wire [6:0]  _idx_history_T_7 =
    io_f1_req_ghist[6:0] ^ io_f1_req_ghist[13:7] ^ io_f1_req_ghist[20:14]
    ^ io_f1_req_ghist[27:21] ^ io_f1_req_ghist[34:28] ^ io_f1_req_ghist[41:35]
    ^ io_f1_req_ghist[48:42] ^ io_f1_req_ghist[55:49] ^ io_f1_req_ghist[62:56];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25
  wire [6:0]  s1_hashed_idx =
    io_f1_req_pc[9:3]
    ^ {_idx_history_T_7[6:1], _idx_history_T_7[0] ^ io_f1_req_ghist[63]};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25, :60:29, generators/boom/src/main/scala/v4/ifu/frontend.scala:149:35
  reg  [8:0]  s2_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:96:29
  reg  [18:0] clear_u_ctr;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:109:28
  wire        doing_clear_u = clear_u_ctr[10:0] == 11'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:109:28, :112:{34,61}
  wire [6:0]  _idx_history_T_15 =
    io_update_hist[6:0] ^ io_update_hist[13:7] ^ io_update_hist[20:14]
    ^ io_update_hist[27:21] ^ io_update_hist[34:28] ^ io_update_hist[41:35]
    ^ io_update_hist[48:42] ^ io_update_hist[55:49] ^ io_update_hist[62:56];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25
  wire [6:0]  update_idx =
    io_update_pc[9:3]
    ^ {_idx_history_T_15[6:1], _idx_history_T_15[0] ^ io_update_hist[63]};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25, :60:29, generators/boom/src/main/scala/v4/ifu/frontend.scala:149:35
  wire [8:0]  _tag_history_T_11 =
    io_update_hist[8:0] ^ io_update_hist[17:9] ^ io_update_hist[26:18]
    ^ io_update_hist[35:27] ^ io_update_hist[44:36] ^ io_update_hist[53:45]
    ^ io_update_hist[62:54];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25
  wire [8:0]  update_tag =
    io_update_pc[18:10]
    ^ {_tag_history_T_11[8:1], _tag_history_T_11[0] ^ io_update_hist[63]};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25, :62:{30,50}, generators/boom/src/main/scala/v4/ifu/frontend.scala:149:35
  wire        _wen_T = io_update_mask_0 | io_update_mask_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:121:60
  assign s2_req_rtage_0_tag = _tage_table_64_ext_R0_data[11:3];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_0_valid = _tage_table_64_ext_R0_data[12];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_1_tag = _tage_table_64_ext_R0_data[24:16];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_1_valid = _tage_table_64_ext_R0_data[25];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_2_tag = _tage_table_64_ext_R0_data[37:29];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_2_valid = _tage_table_64_ext_R0_data[38];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_3_tag = _tage_table_64_ext_R0_data[50:42];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign s2_req_rtage_3_valid = _tage_table_64_ext_R0_data[51];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :126:49
  assign wdata_0 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_0_ctr};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :62:50, :72:28, :130:{20,41,114}, :168:33
  assign wdata_1 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_1_ctr};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :62:50, :72:28, :130:{20,41,114}, :168:33
  assign wdata_2 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_2_ctr};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :62:50, :72:28, :130:{20,41,114}, :168:33
  assign wdata_3 = doing_reset ? 13'h0 : {1'h1, update_tag, update_wdata_3_ctr};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :62:50, :72:28, :130:{20,41,114}, :168:33
  wire        _wdata_T_4 = doing_reset | doing_clear_u;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28, :112:61, :136:43
  assign wdata_1_0 = ~_wdata_T_4 & io_update_u_0[0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_1 = ~_wdata_T_4 & io_update_u_0[1];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_2 = ~_wdata_T_4 & io_update_u_1[0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_3 = ~_wdata_T_4 & io_update_u_1[1];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_4 = ~_wdata_T_4 & io_update_u_2[0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_5 = ~_wdata_T_4 & io_update_u_2[1];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_6 = ~_wdata_T_4 & io_update_u_3[0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  assign wdata_1_7 = ~_wdata_T_4 & io_update_u_3[1];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:43, :145:{20,117}
  reg  [8:0]  wrbypass_tags_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29
  reg  [8:0]  wrbypass_tags_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29
  reg  [6:0]  wrbypass_idxs_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:155:29
  reg  [6:0]  wrbypass_idxs_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:155:29
  reg  [2:0]  wrbypass_0_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_0_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_0_2;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_0_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_1_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_1_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_1_2;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg  [2:0]  wrbypass_1_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29
  reg         wrbypass_enq_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:157:33
  wire        wrbypass_hits_0 =
    ~doing_reset & wrbypass_tags_0 == update_tag & wrbypass_idxs_0 == update_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29, :62:50, :72:28, :100:83, :154:29, :155:29, :161:{22,37}, :162:22
  wire        wrbypass_hit =
    wrbypass_hits_0 | ~doing_reset & wrbypass_tags_1 == update_tag
    & wrbypass_idxs_1 == update_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29, :62:50, :72:28, :100:83, :154:29, :155:29, :161:{22,37}, :162:22, :164:48
  wire [2:0]  _update_wdata_0_ctr_T = io_update_taken_0 ? 3'h4 : 3'h3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:169:10
  wire [2:0]  _GEN = wrbypass_hits_0 ? wrbypass_0_0 : wrbypass_1_0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :156:29, :161:37
  wire [2:0]  _GEN_0 = wrbypass_hits_0 ? wrbypass_0_1 : wrbypass_1_1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :156:29, :161:37
  wire [2:0]  _GEN_1 = wrbypass_hits_0 ? wrbypass_0_2 : wrbypass_1_2;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :156:29, :161:37
  wire [2:0]  _GEN_2 = wrbypass_hits_0 ? wrbypass_0_3 : wrbypass_1_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :156:29, :161:37
  wire        _update_wdata_0_ctr_T_2 = _GEN == 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :124:33
  wire [2:0]  _update_wdata_0_ctr_T_3 = _GEN - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}
  wire [2:0]  _update_wdata_0_ctr_T_7 = _GEN + 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}, :68:43
  wire [2:0]  _update_wdata_0_ctr_T_20 =
    io_update_taken_0
      ? ((&io_update_old_ctr_0) ? 3'h7 : io_update_old_ctr_0 + 3'h1)
      : io_update_old_ctr_0 == 3'h0 ? 3'h0 : io_update_old_ctr_0 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33
  assign update_wdata_0_ctr =
    io_update_alloc_0
      ? _update_wdata_0_ctr_T
      : wrbypass_hit
          ? (io_update_taken_0
               ? ((&_GEN) ? 3'h7 : _update_wdata_0_ctr_T_7)
               : _update_wdata_0_ctr_T_2 ? 3'h0 : _update_wdata_0_ctr_T_3)
          : _update_wdata_0_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33, :164:48, :168:33, :169:10, :172:10
  wire [2:0]  _update_wdata_1_ctr_T = io_update_taken_1 ? 3'h4 : 3'h3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:169:10
  wire        _update_wdata_1_ctr_T_2 = _GEN_0 == 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :124:33
  wire [2:0]  _update_wdata_1_ctr_T_3 = _GEN_0 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}
  wire [2:0]  _update_wdata_1_ctr_T_7 = _GEN_0 + 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}, :68:43
  wire [2:0]  _update_wdata_1_ctr_T_20 =
    io_update_taken_1
      ? ((&io_update_old_ctr_1) ? 3'h7 : io_update_old_ctr_1 + 3'h1)
      : io_update_old_ctr_1 == 3'h0 ? 3'h0 : io_update_old_ctr_1 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33
  assign update_wdata_1_ctr =
    io_update_alloc_1
      ? _update_wdata_1_ctr_T
      : wrbypass_hit
          ? (io_update_taken_1
               ? ((&_GEN_0) ? 3'h7 : _update_wdata_1_ctr_T_7)
               : _update_wdata_1_ctr_T_2 ? 3'h0 : _update_wdata_1_ctr_T_3)
          : _update_wdata_1_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33, :164:48, :168:33, :169:10, :172:10
  wire [2:0]  _update_wdata_2_ctr_T = io_update_taken_2 ? 3'h4 : 3'h3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:169:10
  wire        _update_wdata_2_ctr_T_2 = _GEN_1 == 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :124:33
  wire [2:0]  _update_wdata_2_ctr_T_3 = _GEN_1 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}
  wire [2:0]  _update_wdata_2_ctr_T_7 = _GEN_1 + 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}, :68:43
  wire [2:0]  _update_wdata_2_ctr_T_20 =
    io_update_taken_2
      ? ((&io_update_old_ctr_2) ? 3'h7 : io_update_old_ctr_2 + 3'h1)
      : io_update_old_ctr_2 == 3'h0 ? 3'h0 : io_update_old_ctr_2 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33
  assign update_wdata_2_ctr =
    io_update_alloc_2
      ? _update_wdata_2_ctr_T
      : wrbypass_hit
          ? (io_update_taken_2
               ? ((&_GEN_1) ? 3'h7 : _update_wdata_2_ctr_T_7)
               : _update_wdata_2_ctr_T_2 ? 3'h0 : _update_wdata_2_ctr_T_3)
          : _update_wdata_2_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33, :164:48, :168:33, :169:10, :172:10
  wire [2:0]  _update_wdata_3_ctr_T = io_update_taken_3 ? 3'h4 : 3'h3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:169:10
  wire        _update_wdata_3_ctr_T_2 = _GEN_2 == 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :124:33
  wire [2:0]  _update_wdata_3_ctr_T_3 = _GEN_2 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}
  wire [2:0]  _update_wdata_3_ctr_T_7 = _GEN_2 + 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{25,43}, :68:43
  wire [2:0]  _update_wdata_3_ctr_T_20 =
    io_update_taken_3
      ? ((&io_update_old_ctr_3) ? 3'h7 : io_update_old_ctr_3 + 3'h1)
      : io_update_old_ctr_3 == 3'h0 ? 3'h0 : io_update_old_ctr_3 - 3'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33
  assign update_wdata_3_ctr =
    io_update_alloc_3
      ? _update_wdata_3_ctr_T
      : wrbypass_hit
          ? (io_update_taken_3
               ? ((&_GEN_2) ? 3'h7 : _update_wdata_3_ctr_T_7)
               : _update_wdata_3_ctr_T_2 ? 3'h0 : _update_wdata_3_ctr_T_3)
          : _update_wdata_3_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:{8,20,25,43}, :68:{20,25,43}, :124:33, :164:48, :168:33, :169:10, :172:10
  always @(posedge clock) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
    automatic logic [8:0] _tag_history_T_5 =
      io_f1_req_ghist[8:0] ^ io_f1_req_ghist[17:9] ^ io_f1_req_ghist[26:18]
      ^ io_f1_req_ghist[35:27] ^ io_f1_req_ghist[44:36] ^ io_f1_req_ghist[53:45]
      ^ io_f1_req_ghist[62:54];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25
    automatic logic       _GEN_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:180:32
    automatic logic       _GEN_4;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :180:38, :181:39
    automatic logic       _GEN_5;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :180:38, :181:39
    _GEN_3 = _wen_T | io_update_mask_2 | io_update_mask_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:121:60, :180:32
    _GEN_4 = ~_GEN_3 | wrbypass_hit | wrbypass_enq_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :157:33, :164:48, :180:{32,38}, :181:39
    _GEN_5 = ~_GEN_3 | wrbypass_hit | ~wrbypass_enq_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :157:33, :164:48, :180:{32,38}, :181:39, :185:39
    if (reset) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      doing_reset <= 1'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28
      reset_idx <= 7'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:73:26
      clear_u_ctr <= 19'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:109:28
      wrbypass_enq_idx <= 1'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :157:33
    end
    else begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      doing_reset <= reset_idx != 7'h7F & doing_reset;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28, :73:26, :75:{19,36,50}
      reset_idx <= reset_idx + {6'h0, doing_reset};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28, :73:26, :74:26
      if (doing_reset)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28
        clear_u_ctr <= 19'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:109:28, :110:36
      else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28
        clear_u_ctr <= clear_u_ctr + 19'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:109:28, :110:{36,85}
      if (~_GEN_3 | wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :157:33, :164:48, :180:{32,38}, :181:39
      end
      else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:157:33, :180:38, :181:39
        wrbypass_enq_idx <= wrbypass_enq_idx - 1'h1;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:157:33, generators/boom/src/main/scala/v4/util/util.scala:211:14
    end
    s2_tag <=
      io_f1_req_pc[18:10]
      ^ {_tag_history_T_5[8:1], _tag_history_T_5[0] ^ io_f1_req_ghist[63]};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:53:11, :55:25, :62:{30,50}, :96:29, generators/boom/src/main/scala/v4/ifu/frontend.scala:149:35
    if (_GEN_4) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :180:38, :181:39
    end
    else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :180:38, :181:39
      wrbypass_tags_0 <= update_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:62:50, :154:29
    if (_GEN_5) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :180:38, :181:39
    end
    else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :180:38, :181:39
      wrbypass_tags_1 <= update_tag;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:62:50, :154:29
    if (_GEN_4) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :155:29, :180:38, :181:39
    end
    else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:155:29, :180:38, :181:39
      wrbypass_idxs_0 <= update_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29, :155:29
    if (_GEN_5) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:154:29, :155:29, :180:38, :181:39
    end
    else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:155:29, :180:38, :181:39
      wrbypass_idxs_1 <= update_idx;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29, :155:29
    if (_GEN_3) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:180:32
      if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
        if (wrbypass_hits_0) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:161:37
          if (io_update_alloc_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_0_0 <= _update_wdata_0_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_0) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_0_0 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_0_0 <= _update_wdata_0_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_0_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_0 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_0 <= _update_wdata_0_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_0_0 <= _update_wdata_0_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
          if (io_update_alloc_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_0_1 <= _update_wdata_1_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_1) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_0_1 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_0_1 <= _update_wdata_1_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_1_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_1 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_1 <= _update_wdata_1_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_0_1 <= _update_wdata_1_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
          if (io_update_alloc_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_0_2 <= _update_wdata_2_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_2) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_0_2 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_0_2 <= _update_wdata_2_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_2_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_2 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_2 <= _update_wdata_2_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_0_2 <= _update_wdata_2_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
          if (io_update_alloc_3)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_0_3 <= _update_wdata_3_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_3) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_0_3 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_0_3 <= _update_wdata_3_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_3_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_3 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_0_3 <= _update_wdata_3_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_0_3 <= _update_wdata_3_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        end
        else begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:161:37
          if (io_update_alloc_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_1_0 <= _update_wdata_0_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_0) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_1_0 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_1_0 <= _update_wdata_0_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_0_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_0 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_0 <= _update_wdata_0_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_1_0 <= _update_wdata_0_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
          if (io_update_alloc_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_1_1 <= _update_wdata_1_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_1) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_1_1 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_1_1 <= _update_wdata_1_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_1_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_1 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_1 <= _update_wdata_1_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_1_1 <= _update_wdata_1_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
          if (io_update_alloc_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_1_2 <= _update_wdata_2_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_2) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_1_2 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_1_2 <= _update_wdata_2_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_2_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_2 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_2 <= _update_wdata_2_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_1_2 <= _update_wdata_2_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
          if (io_update_alloc_3)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            wrbypass_1_3 <= _update_wdata_3_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
          else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            if (io_update_taken_3) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
              if (&_GEN_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
                wrbypass_1_3 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
              else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
                wrbypass_1_3 <= _update_wdata_3_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
            end
            else if (_update_wdata_3_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_3 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
              wrbypass_1_3 <= _update_wdata_3_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
          end
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
            wrbypass_1_3 <= _update_wdata_3_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        end
      end
      else if (wrbypass_enq_idx) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:157:33
        if (io_update_alloc_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_1_0 <= _update_wdata_0_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_0) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_1_0 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_1_0 <= _update_wdata_0_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_0_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_0 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_0 <= _update_wdata_0_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_1_0 <= _update_wdata_0_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        if (io_update_alloc_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_1_1 <= _update_wdata_1_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_1) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_1_1 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_1_1 <= _update_wdata_1_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_1_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_1 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_1 <= _update_wdata_1_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_1_1 <= _update_wdata_1_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        if (io_update_alloc_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_1_2 <= _update_wdata_2_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_2) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_1_2 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_1_2 <= _update_wdata_2_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_2_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_2 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_2 <= _update_wdata_2_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_1_2 <= _update_wdata_2_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        if (io_update_alloc_3)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_1_3 <= _update_wdata_3_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_3) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_1_3 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_1_3 <= _update_wdata_3_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_3_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_3 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_1_3 <= _update_wdata_3_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_1_3 <= _update_wdata_3_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
      end
      else begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:157:33
        if (io_update_alloc_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_0_0 <= _update_wdata_0_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_0) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_0_0 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_0_0 <= _update_wdata_0_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_0_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_0 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_0 <= _update_wdata_0_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_0_0 <= _update_wdata_0_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        if (io_update_alloc_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_0_1 <= _update_wdata_1_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_1) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN_0)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_0_1 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_0_1 <= _update_wdata_1_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_1_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_1 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_1 <= _update_wdata_1_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_0_1 <= _update_wdata_1_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        if (io_update_alloc_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_0_2 <= _update_wdata_2_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_2) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN_1)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_0_2 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_0_2 <= _update_wdata_2_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_2_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_2 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_2 <= _update_wdata_2_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_0_2 <= _update_wdata_2_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
        if (io_update_alloc_3)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
          wrbypass_0_3 <= _update_wdata_3_ctr_T;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:156:29, :169:10
        else if (wrbypass_hit) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          if (io_update_taken_3) begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:31:14
            if (&_GEN_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25, :68:25
              wrbypass_0_3 <= 3'h7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25, :156:29
            else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:25
              wrbypass_0_3 <= _update_wdata_3_ctr_T_7;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:68:43, :156:29
          end
          else if (_update_wdata_3_ctr_T_2)	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_3 <= 3'h0;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:124:33, :156:29
          else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:25
            wrbypass_0_3 <= _update_wdata_3_ctr_T_3;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:43, :156:29
        end
        else	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:164:48
          wrbypass_0_3 <= _update_wdata_3_ctr_T_20;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:67:8, :156:29
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      `FIRRTL_BEFORE_INITIAL	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      automatic logic [31:0] _RANDOM[0:2];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      `ifdef INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
        `INIT_RANDOM_PROLOG_	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
        end	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
        doing_reset = _RANDOM[2'h0][0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28
        reset_idx = _RANDOM[2'h0][7:1];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :73:26
        s2_tag = _RANDOM[2'h0][16:8];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :96:29
        clear_u_ctr = {_RANDOM[2'h0][31:17], _RANDOM[2'h1][3:0]};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :109:28
        wrbypass_tags_0 = _RANDOM[2'h1][13:5];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :109:28, :154:29
        wrbypass_tags_1 = _RANDOM[2'h1][22:14];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :109:28, :154:29
        wrbypass_idxs_0 = _RANDOM[2'h1][29:23];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :109:28, :155:29
        wrbypass_idxs_1 = {_RANDOM[2'h1][31:30], _RANDOM[2'h2][4:0]};	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :109:28, :155:29
        wrbypass_0_0 = _RANDOM[2'h2][7:5];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_0_1 = _RANDOM[2'h2][10:8];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_0_2 = _RANDOM[2'h2][13:11];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_0_3 = _RANDOM[2'h2][16:14];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_1_0 = _RANDOM[2'h2][19:17];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_1_1 = _RANDOM[2'h2][22:20];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_1_2 = _RANDOM[2'h2][25:23];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_1_3 = _RANDOM[2'h2][28:26];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :156:29
        wrbypass_enq_idx = _RANDOM[2'h2][29];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :155:29, :157:33
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
      `FIRRTL_AFTER_INITIAL	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  tage_u_128x8 tage_u_64_ext (	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:89:27
    .R0_addr (s1_hashed_idx),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_tage_u_64_ext_R0_data),
    .W0_addr (doing_reset ? reset_idx : doing_clear_u ? clear_u_ctr[17:11] : update_idx),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29, :72:28, :73:26, :109:28, :112:61, :115:33, :144:{19,47}
    .W0_en
      (_wdata_T_4 | io_update_u_mask_0 | io_update_u_mask_1 | io_update_u_mask_2
       | io_update_u_mask_3),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:136:{43,60}
    .W0_clk  (clock),
    .W0_data
      ({wdata_1_7,
        wdata_1_6,
        wdata_1_5,
        wdata_1_4,
        wdata_1_3,
        wdata_1_2,
        wdata_1_1,
        wdata_1_0}),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:89:27, :145:20
    .W0_mask
      (doing_reset
         ? 8'hFF
         : doing_clear_u
             ? {clear_u_ctr[18],
                ~(clear_u_ctr[18]),
                clear_u_ctr[18],
                ~(clear_u_ctr[18]),
                clear_u_ctr[18],
                ~(clear_u_ctr[18]),
                clear_u_ctr[18],
                ~(clear_u_ctr[18])}
             : {{2{io_update_u_mask_3}},
                {2{io_update_u_mask_2}},
                {2{io_update_u_mask_1}},
                {2{io_update_u_mask_0}}})	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28, :109:28, :112:61, :113:31, :114:72, :116:109, :146:{20,34,62,106}
  );
  tage_table_128x52 tage_table_64_ext (	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27
    .R0_addr (s1_hashed_idx),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29
    .R0_en   (io_f1_req_valid),
    .R0_clk  (clock),
    .R0_data (_tage_table_64_ext_R0_data),
    .W0_addr (doing_reset ? reset_idx : update_idx),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:60:29, :72:28, :73:26, :129:19
    .W0_en   (doing_reset | _wen_T | io_update_mask_2 | io_update_mask_3),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28, :121:{34,60}
    .W0_clk  (clock),
    .W0_data ({wdata_3, wdata_2, wdata_1, wdata_0}),	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:90:27, :130:20
    .W0_mask
      (doing_reset
         ? 4'hF
         : {io_update_mask_3, io_update_mask_2, io_update_mask_1, io_update_mask_0})	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:72:28, :131:{20,34,70}
  );
  assign io_f2_resp_0_valid =
    s2_req_rtage_0_valid & s2_req_rtage_0_tag == s2_tag & ~doing_reset;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :96:29, :100:{69,80,83}, :126:49
  assign io_f2_resp_0_bits_ctr = _tage_table_64_ext_R0_data[2:0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :90:27, :126:49
  assign io_f2_resp_0_bits_u = _tage_u_64_ext_R0_data[1:0];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :89:27, :105:34
  assign io_f2_resp_1_valid =
    s2_req_rtage_1_valid & s2_req_rtage_1_tag == s2_tag & ~doing_reset;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :96:29, :100:{69,80,83}, :126:49
  assign io_f2_resp_1_bits_ctr = _tage_table_64_ext_R0_data[15:13];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :90:27, :126:49
  assign io_f2_resp_1_bits_u = _tage_u_64_ext_R0_data[3:2];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :89:27, :105:34
  assign io_f2_resp_2_valid =
    s2_req_rtage_2_valid & s2_req_rtage_2_tag == s2_tag & ~doing_reset;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :96:29, :100:{69,80,83}, :126:49
  assign io_f2_resp_2_bits_ctr = _tage_table_64_ext_R0_data[28:26];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :90:27, :126:49
  assign io_f2_resp_2_bits_u = _tage_u_64_ext_R0_data[5:4];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :89:27, :105:34
  assign io_f2_resp_3_valid =
    s2_req_rtage_3_valid & s2_req_rtage_3_tag == s2_tag & ~doing_reset;	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :72:28, :96:29, :100:{69,80,83}, :126:49
  assign io_f2_resp_3_bits_ctr = _tage_table_64_ext_R0_data[41:39];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :90:27, :126:49
  assign io_f2_resp_3_bits_u = _tage_u_64_ext_R0_data[7:6];	// generators/boom/src/main/scala/v4/ifu/bpd/tage.scala:24:7, :89:27, :105:34
endmodule

