// Generated by CIRCT firtool-1.62.1-1-gdf5ed6ea5
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module TLFIFOFixer_3(	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  input         clock,	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
                reset,	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  output        auto_anon_in_a_ready,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input         auto_anon_in_a_valid,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [2:0]  auto_anon_in_a_bits_opcode,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
                auto_anon_in_a_bits_param,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [3:0]  auto_anon_in_a_bits_size,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [4:0]  auto_anon_in_a_bits_source,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [27:0] auto_anon_in_a_bits_address,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [7:0]  auto_anon_in_a_bits_mask,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [63:0] auto_anon_in_a_bits_data,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input         auto_anon_in_a_bits_corrupt,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
                auto_anon_in_d_ready,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output        auto_anon_in_d_valid,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [2:0]  auto_anon_in_d_bits_opcode,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [1:0]  auto_anon_in_d_bits_param,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [3:0]  auto_anon_in_d_bits_size,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [4:0]  auto_anon_in_d_bits_source,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output        auto_anon_in_d_bits_sink,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
                auto_anon_in_d_bits_denied,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [63:0] auto_anon_in_d_bits_data,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output        auto_anon_in_d_bits_corrupt,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input         auto_anon_out_a_ready,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output        auto_anon_out_a_valid,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [2:0]  auto_anon_out_a_bits_opcode,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
                auto_anon_out_a_bits_param,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [3:0]  auto_anon_out_a_bits_size,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [4:0]  auto_anon_out_a_bits_source,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [27:0] auto_anon_out_a_bits_address,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [7:0]  auto_anon_out_a_bits_mask,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output [63:0] auto_anon_out_a_bits_data,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  output        auto_anon_out_a_bits_corrupt,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
                auto_anon_out_d_ready,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input         auto_anon_out_d_valid,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [2:0]  auto_anon_out_d_bits_opcode,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [1:0]  auto_anon_out_d_bits_param,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [3:0]  auto_anon_out_d_bits_size,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [4:0]  auto_anon_out_d_bits_source,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input         auto_anon_out_d_bits_sink,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
                auto_anon_out_d_bits_denied,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input  [63:0] auto_anon_out_d_bits_data,	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
  input         auto_anon_out_d_bits_corrupt	// generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25
);

  wire [2:0] _a_id_T_31 =
    {{auto_anon_in_a_bits_address[27],
      auto_anon_in_a_bits_address[25],
      auto_anon_in_a_bits_address[16],
      auto_anon_in_a_bits_address[13]} == 4'h0,
     1'h0,
     {auto_anon_in_a_bits_address[27],
      auto_anon_in_a_bits_address[25],
      auto_anon_in_a_bits_address[16],
      ~(auto_anon_in_a_bits_address[13])} == 4'h0}
    | ({auto_anon_in_a_bits_address[27],
        auto_anon_in_a_bits_address[25],
        ~(auto_anon_in_a_bits_address[16])} == 3'h0
         ? 3'h5
         : 3'h0);	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:52:29, :137:{31,41,46,59}, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, src/main/scala/chisel3/util/Mux.scala:30:73
  wire [2:0] a_id =
    {_a_id_T_31[2],
     _a_id_T_31[1:0]
       | {{auto_anon_in_a_bits_address[27],
           ~(auto_anon_in_a_bits_address[25]),
           auto_anon_in_a_bits_address[16]} == 3'h0,
          1'h0} | {2{auto_anon_in_a_bits_address[27]}}};	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:52:29, :137:{31,41,46,59}, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, src/main/scala/chisel3/util/Mux.scala:30:73
  wire       a_noDomain = a_id == 3'h0;	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:52:29, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:63:29, src/main/scala/chisel3/util/Mux.scala:30:73
  reg  [8:0] a_first_counter;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
  wire       a_first = a_first_counter == 9'h0;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25
  reg  [8:0] d_first_counter;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
  reg        flight_0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_1;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_2;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_3;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_4;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_5;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_6;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_7;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_8;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_9;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_10;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_11;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_12;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_13;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_14;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  reg        flight_15;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27
  wire       stalls_a_sel = auto_anon_in_a_bits_source[4:3] == 2'h0;	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  reg  [2:0] stalls_id;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30
  wire       stalls_a_sel_1 = auto_anon_in_a_bits_source[4:3] == 2'h1;	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:{10,32}, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  reg  [2:0] stalls_id_1;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30
  wire       stall =
    stalls_a_sel & a_first
    & (flight_0 | flight_1 | flight_2 | flight_3 | flight_4 | flight_5 | flight_6
       | flight_7) & (a_noDomain | stalls_id != a_id) | stalls_a_sel_1 & a_first
    & (flight_8 | flight_9 | flight_10 | flight_11 | flight_12 | flight_13 | flight_14
       | flight_15) & (a_noDomain | stalls_id_1 != a_id);	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:63:29, :79:27, :85:30, :88:{44,50,65,71}, :91:45, src/main/scala/chisel3/util/Mux.scala:30:73
  wire       anonIn_a_ready = auto_anon_out_a_ready & ~stall;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:91:45, :95:50, :96:33
  always @(posedge clock) begin	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
    automatic logic _stalls_id_T_4;	// src/main/scala/chisel3/util/Decoupled.scala:51:35
    _stalls_id_T_4 = anonIn_a_ready & auto_anon_in_a_valid;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:96:33, src/main/scala/chisel3/util/Decoupled.scala:51:35
    if (reset) begin	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      a_first_counter <= 9'h0;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
      d_first_counter <= 9'h0;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27
      flight_0 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_1 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_2 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_3 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_4 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_5 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_6 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_7 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_8 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_9 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_10 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_11 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_12 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_13 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_14 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
      flight_15 <= 1'h0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
    end
    else begin	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      automatic logic d_first_first;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25
      automatic logic _GEN;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:80:21
      automatic logic _GEN_0;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:81:21
      d_first_first = d_first_counter == 9'h0;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25
      _GEN = a_first & _stalls_id_T_4;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:80:21, src/main/scala/chisel3/util/Decoupled.scala:51:35
      _GEN_0 =
        d_first_first & auto_anon_out_d_bits_opcode != 3'h6 & auto_anon_in_d_ready
        & auto_anon_out_d_valid;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:75:63, :81:21
      if (_stalls_id_T_4) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (a_first) begin	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25
          automatic logic [26:0] _a_first_beats1_decode_T =
            27'hFFF << auto_anon_in_a_bits_size;	// generators/rocket-chip/src/main/scala/util/package.scala:243:71
          a_first_counter <=
            auto_anon_in_a_bits_opcode[2] ? 9'h0 : ~(_a_first_beats1_decode_T[11:3]);	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, :221:14, :229:27, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}
        end
        else	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25
          a_first_counter <= a_first_counter - 9'h1;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28
      end
      if (auto_anon_in_d_ready & auto_anon_out_d_valid) begin	// src/main/scala/chisel3/util/Decoupled.scala:51:35
        if (d_first_first) begin	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25
          automatic logic [26:0] _d_first_beats1_decode_T =
            27'hFFF << auto_anon_out_d_bits_size;	// generators/rocket-chip/src/main/scala/util/package.scala:243:71
          d_first_counter <=
            auto_anon_out_d_bits_opcode[0] ? ~(_d_first_beats1_decode_T[11:3]) : 9'h0;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:106:36, :221:14, :229:27, generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}
        end
        else	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:231:25
          d_first_counter <= d_first_counter - 9'h1;	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28
      end
      flight_0 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h0)
        & (_GEN & auto_anon_in_a_bits_source == 5'h0 | flight_0);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_1 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h1)
        & (_GEN & auto_anon_in_a_bits_source == 5'h1 | flight_1);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_2 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h2)
        & (_GEN & auto_anon_in_a_bits_source == 5'h2 | flight_2);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_3 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h3)
        & (_GEN & auto_anon_in_a_bits_source == 5'h3 | flight_3);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_4 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h4)
        & (_GEN & auto_anon_in_a_bits_source == 5'h4 | flight_4);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_5 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h5)
        & (_GEN & auto_anon_in_a_bits_source == 5'h5 | flight_5);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_6 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h6)
        & (_GEN & auto_anon_in_a_bits_source == 5'h6 | flight_6);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_7 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h7)
        & (_GEN & auto_anon_in_a_bits_source == 5'h7 | flight_7);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_8 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h8)
        & (_GEN & auto_anon_in_a_bits_source == 5'h8 | flight_8);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_9 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'h9)
        & (_GEN & auto_anon_in_a_bits_source == 5'h9 | flight_9);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_10 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'hA)
        & (_GEN & auto_anon_in_a_bits_source == 5'hA | flight_10);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_11 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'hB)
        & (_GEN & auto_anon_in_a_bits_source == 5'hB | flight_11);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_12 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'hC)
        & (_GEN & auto_anon_in_a_bits_source == 5'hC | flight_12);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_13 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'hD)
        & (_GEN & auto_anon_in_a_bits_source == 5'hD | flight_13);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_14 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'hE)
        & (_GEN & auto_anon_in_a_bits_source == 5'hE | flight_14);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
      flight_15 <=
        ~(_GEN_0 & auto_anon_out_d_bits_source == 5'hF)
        & (_GEN & auto_anon_in_a_bits_source == 5'hF | flight_15);	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:79:27, :80:{21,35,62}, :81:{21,35,62}
    end
    if (_stalls_id_T_4 & stalls_a_sel)	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:47, src/main/scala/chisel3/util/Decoupled.scala:51:35
      stalls_id <= a_id;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30, src/main/scala/chisel3/util/Mux.scala:30:73
    if (_stalls_id_T_4 & stalls_a_sel_1)	// generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:54:32, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:47, src/main/scala/chisel3/util/Decoupled.scala:51:35
      stalls_id_1 <= a_id;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:85:30, src/main/scala/chisel3/util/Mux.scala:30:73
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
    `ifdef FIRRTL_BEFORE_INITIAL	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      `FIRRTL_BEFORE_INITIAL	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      automatic logic [31:0] _RANDOM[0:1];	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      `ifdef INIT_RANDOM_PROLOG_	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
        `INIT_RANDOM_PROLOG_	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
        end	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
        a_first_counter = _RANDOM[1'h0][8:0];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
        d_first_counter = _RANDOM[1'h0][17:9];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
        flight_0 = _RANDOM[1'h0][18];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_1 = _RANDOM[1'h0][19];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_2 = _RANDOM[1'h0][20];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_3 = _RANDOM[1'h0][21];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_4 = _RANDOM[1'h0][22];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_5 = _RANDOM[1'h0][23];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_6 = _RANDOM[1'h0][24];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_7 = _RANDOM[1'h0][25];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_8 = _RANDOM[1'h0][26];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_9 = _RANDOM[1'h0][27];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_10 = _RANDOM[1'h0][28];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_11 = _RANDOM[1'h0][29];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_12 = _RANDOM[1'h0][30];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_13 = _RANDOM[1'h0][31];	// generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_14 = _RANDOM[1'h1][0];	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        flight_15 = _RANDOM[1'h1][1];	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27
        stalls_id = _RANDOM[1'h1][9:7];	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27, :85:30
        stalls_id_1 = _RANDOM[1'h1][12:10];	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :79:27, :85:30
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
      `FIRRTL_AFTER_INITIAL	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_8 monitor (	// generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (anonIn_a_ready),	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:96:33
    .io_in_a_valid        (auto_anon_in_a_valid),
    .io_in_a_bits_opcode  (auto_anon_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_anon_in_a_bits_param),
    .io_in_a_bits_size    (auto_anon_in_a_bits_size),
    .io_in_a_bits_source  (auto_anon_in_a_bits_source),
    .io_in_a_bits_address (auto_anon_in_a_bits_address),
    .io_in_a_bits_mask    (auto_anon_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_anon_in_a_bits_corrupt),
    .io_in_d_ready        (auto_anon_in_d_ready),
    .io_in_d_valid        (auto_anon_out_d_valid),
    .io_in_d_bits_opcode  (auto_anon_out_d_bits_opcode),
    .io_in_d_bits_param   (auto_anon_out_d_bits_param),
    .io_in_d_bits_size    (auto_anon_out_d_bits_size),
    .io_in_d_bits_source  (auto_anon_out_d_bits_source),
    .io_in_d_bits_sink    (auto_anon_out_d_bits_sink),
    .io_in_d_bits_denied  (auto_anon_out_d_bits_denied),
    .io_in_d_bits_corrupt (auto_anon_out_d_bits_corrupt)
  );
  assign auto_anon_in_a_ready = anonIn_a_ready;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :96:33
  assign auto_anon_in_d_valid = auto_anon_out_d_valid;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_opcode = auto_anon_out_d_bits_opcode;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_param = auto_anon_out_d_bits_param;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_size = auto_anon_out_d_bits_size;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_source = auto_anon_out_d_bits_source;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_sink = auto_anon_out_d_bits_sink;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_denied = auto_anon_out_d_bits_denied;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_data = auto_anon_out_d_bits_data;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_in_d_bits_corrupt = auto_anon_out_d_bits_corrupt;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_valid = auto_anon_in_a_valid & ~stall;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9, :91:45, :95:{33,50}
  assign auto_anon_out_a_bits_opcode = auto_anon_in_a_bits_opcode;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_param = auto_anon_in_a_bits_param;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_size = auto_anon_in_a_bits_size;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_source = auto_anon_in_a_bits_source;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_address = auto_anon_in_a_bits_address;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_mask = auto_anon_in_a_bits_mask;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_data = auto_anon_in_a_bits_data;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_a_bits_corrupt = auto_anon_in_a_bits_corrupt;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
  assign auto_anon_out_d_ready = auto_anon_in_d_ready;	// generators/rocket-chip/src/main/scala/tilelink/FIFOFixer.scala:50:9
endmodule

